### ISSUE TITLE
js-bson: Failed to load c++ bson extension, using pure JS version

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1003]
Hello,

I tried to install mean on an arch linux computer. I get this error after typing 'grunt':

```
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/projects/mean/bower_components/jquery/dist/jquery.min.map'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at module.exports (/projects/mean/node_modules/meanio/lib/bootstrap.js:31:27)
    at /projects/mean/node_modules/meanio/lib/mean.js:20:27
    at Config.onPackageRead (/projects/mean/node_modules/meanio/lib/config.js:101:25)
    at Promise.<anonymous> (/projects/mean/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/projects/mean/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/projects/mean/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Object.cb (/projects/mean/node_modules/mongoose/lib/query.js:1146:30)
[nodemon] app crashed - waiting for file changes before starting...
```

node version: v0.10.35
npm version: 2.1.18
MongoDB shell version: 2.6.6

What can I do??

**Comment by manonthemoon42** [comment]
Really, the solution should be published before closing the issue !

**Comment by BrockMcKean** [comment]
Do you have this issue @manonthemoon42 ?

**Comment by manonthemoon42** [comment]
Okay... 
I resolved it. 

In the documentation, it says that we have to do `npm install`.
But it never showed the command `bower install`. 
The bower.json contains all the tools needed for the mean stack! AngularJS, Express, Jquery... But it has to be installed with this command : `bower install` .
Wouldn't be good to add it in the documentation ?

**Comment by BrockMcKean** [comment]
Do a PR on the README  or I'll do it when I get to it after we hunt down these problems with a test.

**Comment by manonthemoon42** [comment]
Okay, I'll do a pull request.

Thank you

Le Tue Jan 27 2015 at 21:07:41, Brock McKean <notifications@github.com> a
écrit :
