### ISSUE TITLE
Installing mean on a linux system, Step by step.

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1009]
Hi,

I am facing huge difficulties installing my project on an archlinux system. I don't find documetation or help.
So I will try to explain you what I did, step by step. Feel free to tell me what is good/wrong, then I will retest the new method from scratch over and over until I get a fully working guide on 'how the hell you can install mean on a linux system when your are a complete noob'.

So for the moment here is what I did:

#### ```NODE_ENV=production grunt```

For the moment it's not working (I open another issue for that), but if you see something wrong or something I can improve, or if this is not the good way to do, our anything, please comment.

Thank you

**Comment by Tyvain** [comment]
So I have been trying from the start (I even reinstall archlinux). Everything is ok until npm install:

```
> kerberos@0.0.4 install /home/tyvain/fast-annonces/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/tyvain/fast-annonces/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
kerberos.target.mk:20: recipe for target 'Release/obj.target/kerberos.node' failed
make: Leaving directory '/home/tyvain/fast-annonces/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'

> bson@0.2.17 install /home/tyvain/fast-annonces/node_modules/connect-mongo/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/tyvain/fast-annonces/node_modules/connect-mongo/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
bson.target.mk:80: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
make: Leaving directory '/home/tyvain/fast-annonces/node_modules/connect-mongo/node_modules/mongodb/node_modules/bson/build'

> bson@0.2.17 install /home/tyvain/fast-annonces/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/tyvain/fast-annonces/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
bson.target.mk:80: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
make: Leaving directory '/home/tyvain/fast-annonces/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'

> ws@0.4.32 install /home/tyvain/fast-annonces/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/tyvain/fast-annonces/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:83: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/home/tyvain/fast-annonces/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm ERR! cb() never called!
```

Any idea?

**Comment by Tyvain** [comment]
hee is the builerro.log:

```
[root@alarm build]# cd /home/tyvain/fast-annonces/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
[root@alarm ws]# cat builderror.log
make: g++: Command not found
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.14.27-2-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tyvain/fast-annonces/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by Tyvain** [comment]
solved:
npm install -g node-gyp
npm install -g browserify
