### ISSUE TITLE
Cannot find module 'browserify-zlib'

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#1015]
after I launch:  NODE_ENV=production grunt

I get this error:

```
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module 'browserify-zlib'
```

any idea?

**Comment by Tyvain** [comment]
solved:
npm install -g browserify

**Comment by edgraaff** [comment]
Exactly the opposite was the case for me; the globally installed browserify version appeared to be conflicting with the one in the current project.
npm uninstall -g browserify

**Comment by lucastelnovo** [comment]
I tried both installing the module and uninstalling it.
Still getting this error when trying to run android

Error: Cannot find module 'browserify-zlib'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/lucastelnovo/Desarrollo/unipool2-client2/node_modules/node-libs-browser/index.js:38:29)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)


any idea?

ionic info:

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.1-201711081842

System:

    Android SDK Tools : 25.2.5
    Node              : v8.6.0
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

Environment Variables:

    ANDROID_HOME : /Users/lucastelnovo/Desarrollo/android-sdk-macosx

Misc:

    backend : pro
