### ISSUE TITLE
npm install problems: (related to 1042). still not able to start server

### ISSUE THREAD

**Issue by laurencefass** [linnovate/mean#1046]
to resolve issue 1042 i have reinstalled grunt and bower and cleared all caches (including npm). i am now seeing a different problem - the app is aborting due to a problem with mongodb and absence of express-session package. i have tried manually installing express-session in mongodb but the error remains.

grunt
Running "hook" task
>> Starting hooked tasks.

Running "clean:0" (clean) task
>> 0 paths cleaned.

Running "jshint:all" (jshint) task
>> 42 files lint free.

Running "csslint:src" (csslint) task
>> 5 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Waiting...
Running "nodemon:dev" (nodemon) task
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858

/home/nodejs.server.com/meanioserver1/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:297
          throw err;
                ^
Error: Cannot find module 'express-session'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/nodejs.server.com/meanioserver1/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
