### ISSUE TITLE
modulePath not defined

### ISSUE THREAD

**Issue by danielskapunk** [linnovate/mean#1065]
Hi, I'm getting modulePath is not defined when trying to render a view like this:
custom/ccwstheme/server/routes/ccwstheme.js
```
Ccwstheme.render('test', {
      package: 'ccwstheme'
    }, function(err, html) {
      //Rendering a view from the Package server/views
      res.send(html);
 });
```

Here is the error:
```
ReferenceError: modulePath is not defined
    at Module.render (C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\module\index.js:162:21)
    at C:\dev\CuriosoWS\meanapp\packages\custom\ccwstheme\server\routes\ccwstheme.js:18:15
    at Layer.handle [as handle_request] (C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\layer.js
:82:5)
    at next (C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\layer.js
:82:5)
    at C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\index.js:267:22
    at Function.proto.process_params (C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\index.js:32
1:12)
    at next (C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\index.js:261:10)
    at SendStream.error (C:\dev\CuriosoWS\meanapp\node_modules\meanio\lib\core_modules\server\node_modules\express\node_modules\serve-static\index.js:
107:7)
```

**Comment by danielskapunk** [comment]
I found there is an open issue in meanio:
https://github.com/linnovate/meanio/issues/42

Is there any workarround?

I'm trying to render with express res.render method instead, any ideas?

**Comment by VikramTiwari** [comment]
This should be fixed by now. Please reopen if still an issue.
