### ISSUE TITLE
Using mean on OSX

### ISSUE THREAD

**Issue by VikramTiwari** [linnovate/mean#1092]
After installation and creating a new project when i try to do `npm install` the following issues occur

```
npm WARN engine meanio@0.7.1: wanted: {"node":"0.10.x","npm":"1.4.x"} (current: {"node":"0.12.0","npm":"2.5.1"})

> meanio@0.7.1 preinstall /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio
> node ./scripts/preinstall

npm WARN engine mean-cli@0.9.20: wanted: {"node":"0.10.x","npm":"2.1.x"} (current: {"node":"0.12.0","npm":"2.5.1"})

> mean-health@0.1.7 postinstall /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/node_modules/mean-health
> node ./postinstall.js

 
> mean-cli@0.9.20 preinstall /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/node_modules/mean-cli
> node ./scripts/preinstall

\
> meanio@0.7.1 postinstall /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio
> cd ./lib/core_modules/server && npm install && cd ../../..

npm WARN package.json server@ No description
npm WARN package.json server@ No repository field.
npm WARN package.json server@ No README data
npm WARN locking Error: EACCES, open '/Users/vikram/.npm/_locks/cookie-parser-63322027e7790f6a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/vikram/.npm/_locks/cookie-parser-63322027e7790f6a.lock failed { [Error: EACCES, open '/Users/vikram/.npm/_locks/cookie-parser-63322027e7790f6a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/vikram/.npm/_locks/cookie-parser-63322027e7790f6a.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/node_modules/cookie-parser, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/vikram/.npm/_locks/connect-mongo-18f02be761350c4a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/vikram/.npm/_locks/connect-mongo-18f02be761350c4a.lock failed { [Error: EACCES, open '/Users/vikram/.npm/_locks/connect-mongo-18f02be761350c4a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/vikram/.npm/_locks/connect-mongo-18f02be761350c4a.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/node_modules/connect-mongo, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/vikram/.npm/_locks/method-override-6f3a82f584347aee.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/vikram/.npm/_locks/method-override-6f3a82f584347aee.lock failed { [Error: EACCES, open '/Users/vikram/.npm/_locks/method-override-6f3a82f584347aee.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/vikram/.npm/_locks/method-override-6f3a82f584347aee.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/node_modules/method-override, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/vikram/.npm/_locks/passport-340b7265fcd8796c.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/vikram/.npm/_locks/passport-340b7265fcd8796c.lock failed { [Error: EACCES, open '/Users/vikram/.npm/_locks/passport-340b7265fcd8796c.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/vikram/.npm/_locks/passport-340b7265fcd8796c.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/node_modules/passport, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/vikram/.npm/_locks/gridfs-stream-c89f8e239f77b547.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/vikram/.npm/_locks/gridfs-stream-c89f8e239f77b547.lock failed { [Error: EACCES, open '/Users/vikram/.npm/_locks/gridfs-stream-c89f8e239f77b547.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/vikram/.npm/_locks/gridfs-stream-c89f8e239f77b547.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/node_modules/gridfs-stream, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/vikram/.npm/_locks/express-validator-9281b29536e981ab.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/vikram/.npm/_locks/express-validator-9281b29536e981ab.lock failed { [Error: EACCES, open '/Users/vikram/.npm/_locks/express-validator-9281b29536e981ab.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/vikram/.npm/_locks/express-validator-9281b29536e981ab.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/node_modules/express-validator, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/vikram/.npm/_locks/express-session-4fee1e57a848d64f.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/vikram/.npm/_locks/express-session-4fee1e57a848d64f.lock failed { [Error: EACCES, open '/Users/vikram/.npm/_locks/express-session-4fee1e57a848d64f.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/vikram/.npm/_locks/express-session-4fee1e57a848d64f.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/node_modules/express-session, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/vikram/.npm/_locks/express-aed2e551fdaeb1fa.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/vikram/.npm/_locks/express-aed2e551fdaeb1fa.lock failed { [Error: EACCES, open '/Users/vikram/.npm/_locks/express-aed2e551fdaeb1fa.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/vikram/.npm/_locks/express-aed2e551fdaeb1fa.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/node_modules/express, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/npm-debug.log
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! meanio@0.7.1 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanio@0.7.1 postinstall script 'cd ./lib/core_modules/server && npm install && cd ../../..'.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vikram/Documents/code/SilverPush/falcon/npm-debug.log
```

**Comment by VikramTiwari** [comment]
This was resolved by providing permissions to the current user. [StackOverflow Question] (http://stackoverflow.com/questions/22152162/npm-cannot-install-dependencies-attempt-to-unlock-something-which-hasnt-been)

But got a successive error while running it with gulp.

```
Vikrams-MacBook-Air:falcon vikram$ gulp
[16:59:53] Using gulpfile ~/Documents/code/SilverPush/falcon/gulpfile.js
[16:59:53] Starting 'clean'...
[16:59:53] Starting 'jshint'...
[16:59:53] Starting 'less'...
[16:59:53] Starting 'csslint'...
[16:59:53] Starting 'env:develop'...
[16:59:53] Finished 'env:develop' after 103 μs
[16:59:53] Starting 'develop'...
[16:59:54] Finished 'develop' after 126 ms
[16:59:54] Starting 'watch'...
[17:00:01] Finished 'watch' after 7.63 s
[17:00:01] Live reload server listening on: 35729
[17:00:01] Finished 'clean' after 8.36 s
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node --debug server.js`
Debugger listening on port 5858
[gulp] [nodemon] watching 31,394 files - this might cause high cpu usage. To reduce use "--watch".
Mean app started on port 3000 (development) cluster.worker.id: 0
/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:107:17)
    at null.<anonymous> (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
[gulp] [nodemon] app crashed - waiting for file changes before starting...
[17:00:08] csslint: 5 files lint free
[17:00:08] Finished 'csslint' after 14 s
[17:00:09] Finished 'less' after 16 s
[17:00:10] jshint: 43 files lint free
[17:00:10] Finished 'jshint' after 17 s
[17:00:10] Starting 'default'...
[17:00:10] Finished 'default' after 10 μs
```

**Comment by VikramTiwari** [comment]
Resolved. DB config was wrong. But i expected better error messages.

**Comment by VikramTiwari** [comment]
So this error was genuine and will always arise whenever the DB config was wrong. This can be fixed with the version update of mongoose as discussed (here) [https://github.com/LearnBoost/mongoose/issues/2757].

**Comment by liorkesos** [comment]
I committed the mongoose version to the latest  - 3.8.24
Should side step this...
Thanks for the details insight
Lior
