### ISSUE TITLE
using local mongo deployment yet failing [Unhandled error]

### ISSUE THREAD

**Issue by VikramTiwari** [linnovate/mean#1101]
Logs
```
Vikrams-MacBook-Air:falcon vikram$ gulp
[12:48:23] Using gulpfile ~/Documents/code/SilverPush/falcon/gulpfile.js
[12:48:23] Starting 'clean'...
[12:48:23] Finished 'clean' after 4.37 ms
[12:48:23] Starting 'default'...
[12:48:23] Starting 'env:develop'...
[12:48:23] Finished 'env:develop' after 29 μs
[12:48:23] Starting 'develop'...
[12:48:23] Finished 'develop' after 123 ms
[12:48:23] Finished 'default' after 125 ms
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node --debug server.js`
Debugger listening on port 5858
[gulp] [nodemon] watching 27,819 files - this might cause high cpu usage. To reduce use "--watch".
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at ExpressEngine.beginBootstrap (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:127:14)
    at Meanio.serveWithDb (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/lib/core_modules/server/index.js:14:10)
    at Consumer.Dependable.runAction (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/node_modules/lazy-dependable/index.js:73:22)
    at Consumer.Dependable.fire (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/node_modules/lazy-dependable/index.js:70:53)
    at Consumer.onResolved (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/node_modules/lazy-dependable/index.js:120:8)
    at Consumer.Dependable.resolve (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/meanio/node_modules/lazy-dependable/index.js:56:10)
[gulp] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by liorkesos** [comment]
Looks like the methong else is listening on port 3000

**Comment by VikramTiwari** [comment]
Hahaha silly me. :) :+1:
