### ISSUE TITLE
Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'

### ISSUE THREAD

**Issue by davecyen** [linnovate/mean#1154]
Hey guys - I'm experiencing a problem that prevents me from deploying to heroku and can't find a solution. This is the error message I get: Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'

I've tried bower install, npm install, bower cache clean, npm cache clean, and npm install --allow-root, but all with no luck.

**Comment by max-mog** [comment]
I'm not sure where your jquery lib is located but if you have it as a part of a custom package, make sure you npm install and bower install from within the package folder also.

**Comment by davecyen** [comment]
Thanks max but I actually haven't installed any jquery libraries

**Comment by max-mog** [comment]
I thought there problem was at '/app/bower_components/jquery/dist/jquery.min.map'.

The other thing I can think of is trying the npm and bower installs with sudo. Hope that works

**Comment by mwizzle** [comment]
I'm having this issue as well, and it only happens in Heroku. In case a stacktrace would provide any insights:

Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'
app[web.1]:     at Error (native)
app[web.1]:     at Object.fs.openSync (fs.js:500:18)
at Object.fs.readFileSync (fs.js:352:15)
at findModulesDone (/app/node_modules/meanio/lib/core_modules/module/index.js:55:27)
app[web.1]:     at _fulfilled (/app/node_modules/meanio/node_modules/q/q.js:820:54)
app[web.1]:     at self.promiseDispatch.done (/app/node_modules/meanio/node_modules/q/q.js:849:30)
app[web.1]:     at Promise.promise.promiseDispatch (/app/node_modules/meanio/node_modules/q/q.js:782:13)
app[web.1]:     at /app/node_modules/meanio/node_modules/q/q.js:590:44
app[web.1]:     at runSingle (/app/node_modules/meanio/node_modules/q/q.js:123:13)
app[web.1]:     at flush (/app/node_modules/meanio/node_modules/q/q.js:111:13)


Also, during deployment to Heroku, I see this error (which may or may not be related):

Error: ENOENT, open '.bower-cache/87323d6d4e48be291a9616a033d4cc6c-1.3.2.lock'


Thoughts?

**Comment by Nicholas-Westley** [comment]
I was getting this error and it was because I was missing bower from my dependencies in my package.json file.

**Comment by BrockMcKean** [comment]
Thanks @Nicholas-Westley ! If you find a simple bug like that please submit a PR if you have time. It helps out a lot. :) Thanks again, I'll fix this and commit to master.

**Comment by RhysJevons** [comment]
I've been seeing the same issue as mwizzle. Has anyone got a solution?

**Comment by RhysJevons** [comment]
Seems like a few people are having the same issue. Here are my logs if it helps:

Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'
2015-06-18T10:17:04.767355+00:00 app[web.1]:     at Object.fs.readFileSync (fs.js:290:15)
2015-06-18T10:17:04.767356+00:00 app[web.1]:     at module.exports (/app/node_modules/meanio/lib/bootstrap.js:31:27)
2015-06-18T10:17:04.767353+00:00 app[web.1]:     at Object.fs.openSync (fs.js:439:18)
2015-06-18T10:17:04.767358+00:00 app[web.1]:     at /app/node_modules/meanio/lib/mean.js:20:27
2015-06-18T10:17:04.767361+00:00 app[web.1]:     at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
2015-06-18T10:17:04.767359+00:00 app[web.1]:     at Config.onPackageRead (/app/node_modules/meanio/lib/config.js:101:25)
2015-06-18T10:17:04.767365+00:00 app[web.1]:     at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
2015-06-18T10:17:04.767364+00:00 app[web.1]:     at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
2015-06-18T10:17:04.767367+00:00 app[web.1]:     at Object.cb (/app/node_modules/mongoose/lib/query.js:1146:30)
2015-06-18T10:17:04.767368+00:00 app[web.1]: 
2015-06-18T10:17:04.767370+00:00 app[web.1]: fs.js:439
2015-06-18T10:17:04.767362+00:00 app[web.1]:     at Promise.emit (events.js:95:17)
2015-06-18T10:17:04.767372+00:00 app[web.1]:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
2015-06-18T10:17:04.767375+00:00 app[web.1]: Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'
2015-06-18T10:17:04.767376+00:00 app[web.1]:     at Object.fs.openSync (fs.js:439:18)
2015-06-18T10:17:04.767377+00:00 app[web.1]:     at Object.fs.readFileSync (fs.js:290:15)
2015-06-18T10:17:04.767379+00:00 app[web.1]:     at module.exports (/app/node_modules/meanio/lib/bootstrap.js:31:27)
2015-06-18T10:17:04.767384+00:00 app[web.1]:     at Config.onPackageRead (/app/node_modules/meanio/lib/config.js:101:25)

**Comment by VikramTiwari** [comment]
As pointed by @Nicholas-Westley this is cause of bower-dependencies not being fulfilled. @RhysJevons  This has been fixed in the latest versions. Reopen if it still persists.

**Comment by shubhangi-tandon** [comment]
I've added bower as a dependency in my package.json and see it cming up in npm-shrinkwrap as well but I'm still seeing this error 
Please advise ?

**Comment by cesaravina** [comment]
I was having the same issue but was able to fix it using jawsdb: 
https://devcenter.heroku.com/articles/jawsdb
From the command line:
$heroku addons:create jawsdb
