### ISSUE TITLE
web page not available at localhost:3000

### ISSUE THREAD

**Issue by swamy526** [linnovate/mean#1163]
while i am trying to run opendhift mean application locally,i am not able to view web page. Here is the command line stack trace:::

Mean app started on port 3000 (development)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:160:15)
    at Server.connect (/Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/lib/server.js:291:17)
    at Db.open (/Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/lib/db.js:190:19)
    at MongoStore._open_database (/Users/swamyk/meantest/node_modules/connect-mongo/lib/connect-mongo.js:182:15)
    at MongoStore._get_collection (/Users/swamyk/meantest/node_modules/connect-mongo/lib/connect-mongo.js:177:14)
    at /Users/swamyk/meantest/node_modules/connect-mongo/lib/connect-mongo.js:194:16
    at /Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/lib/db.js:200:5
    at connectHandler (/Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/lib/server.js:272:7)
    at g (events.js:180:16)
    at emit (events.js:95:17)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:160:15)
    at once (events.js:185:8)
    at connectHandler (/Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/lib/server.js:265:19)
    at g (events.js:180:16)
    at emit (events.js:95:17)
    at /Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:373:23
    at /Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:770:13
    at Callbacks.emit (/Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)
    at null.messageHandler (/Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:218:23)
    at Socket.<anonymous> (/Users/swamyk/meantest/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:259:22)

And
  Os is = OS X 10.9.5
node version = v0.10.35
npm version = 2.8.3
mongodb version = 3.0.2

How can i fix this?

**Comment by VikramTiwari** [comment]
This is fixed in latest versions. Reopen if this is still an issue for you.

**Comment by SrinivasPrabhu794** [comment]
@VikramTiwari Could you please me tell which specific commit fixed that issue? I am trying to take these changes to an older version of mean(0.4.3). I face this issue when updating mongoose from 3.8 to 4.3.7. Any help would be appreciated :)
