### ISSUE TITLE
Newly created app not starting 

### ISSUE THREAD

**Issue by vincentlawlor** [linnovate/mean#1179]
Hi guys,

I have just created a new app. Everything installed fine until I run gulp and it throws the following error. Anybody seen this one before?

/Users/vincentlawlor/workspace/mean/config-manager/node_modules/mongoose/node_modules/mongodb/lib/server.js:274
      process.nextTick(function() { throw err; })
                                          ^
Error: ENOENT, no such file or directory '/Users/vincentlawlor/.mean'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at readToken (/Users/vincentlawlor/workspace/mean/config-manager/node_modules/meanio/lib/notifiers.js:41:19)
    at init (/Users/vincentlawlor/workspace/mean/config-manager/node_modules/meanio/lib/notifiers.js:52:24)
    at Object.<anonymous> (/Users/vincentlawlor/workspace/mean/config-manager/node_modules/meanio/lib/notifiers.js:107:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at accessLog (/Users/vincentlawlor/workspace/mean/config-manager/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:172:19)
    at ExpressEngine.initApp (/Users/vincentlawlor/workspace/mean/config-manager/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:62:17)
    at Dependency.Dependable.runAction (/Users/vincentlawlor/workspace/mean/config-manager/node_modules/meanio/node_modules/lazy-dependable/index.js:73:22)
    at Dependency.runAction (/Users/vincentlawlor/workspace/mean/config-manager/node_modules/meanio/node_modules/lazy-dependable/index.js:98:48)

**Comment by vincentlawlor** [comment]
Tried the same thing on Ubuntu. Exact same error.

**Comment by bk10287** [comment]
I'm seeing this too after doing a pull.  I just made the file and went from there, which led to an error finding this node package: swagger-node-express.  I manually added it to the packages.json file, which led to this: Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=mean&p1=Error%3A%2…000%2Fbower_components%2Fangular%2Fangular.min.js%3F2gndzccjtt9%3A17%3A381).  This is where I am now :(

**Comment by liorkesos** [comment]
After a pull make sure you run npm install.
Rt O create .mean try running a mean register.
It is not mandatory to work with the mean network but we need better edge
case management for upgraders...
Please see if running mean register from the CLI creates the .mean file and
help a out....
Lior

**Comment by vincentlawlor** [comment]
@liorkesos - thanks that worked.
Probably worth updating the documentation on mean.io to reflect the change

**Comment by bk10287** [comment]
@liorkesos I ran a npm install after updating packages.json.  Still having the issue, and when i run a mean register it fails, but i just touched .mean so the file not being there isn't an issue.

**Comment by vincentlawlor** [comment]
@bk10287 - you getting the same error as me?

**Comment by bk10287** [comment]
@vincentlawlor No I got it running, but im getting an error in the browser.  I posted it in another issue, it seems like an inconsistency in upgrading angular-route

**Comment by bk10287** [comment]
ok I got to the root of the issue for me.  The packages in core i had to cd into and individually run bower install on them.  I'm not sure if this can be cascaded down or there is a command switch I am missing, but I would suggest manually running bower install inside any packages that have a bower.json file

**Comment by vincentlawlor** [comment]
@liorkesos - any update on this still have the same problem.

**Comment by bk10287** [comment]
@vincentlawlor did you run bower install on all packages?  Also did you do an npm update and npm cache clean?

**Comment by PhGeek** [comment]
Thanks @bk10287... Helped me a lot! :+1: 

Same error here (package swagger-node-express)

Added ("swagger-node-express": "latest") to package.json then "bower install" on packages core/admin, core/users and custom/i18n.

**Comment by namdp06** [comment]
thanks @bk10287 and @PhGeek 
I fix this error by add ("swagger-node-express": "latest") into package.json which locate on any folder show from debug and it fixed

**Comment by bk10287** [comment]
Awesome! Glad I could help

**Comment by VikramTiwari** [comment]
Fixed.
