### ISSUE TITLE
Deploying to heroku: Error: ENOENT, no such file or directory '/app/.mean'

### ISSUE THREAD

**Issue by polinac** [linnovate/mean#1182]
I followed the instruction  how to deploy the example to Heroku. All commands worked well, but when I started the browser I saw the error: "An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your logs for details."

I checked the logs and found the error:

/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
                                        ^
     process.nextTick(function() { throw err; });
Error: ENOENT, no such file or directory '/app/.mean'
     at Error (native)
     at readToken (/app/node_modules/meanio/lib/notifiers.js:41:19)
     at Object.fs.openSync (fs.js:500:18)
     at Object.fs.readFileSync (fs.js:352:15)
     at init (/app/node_modules/meanio/lib/notifiers.js:52:24)
     at Object.<anonymous> (/app/node_modules/meanio/lib/notifiers.js:107:1)
     at Module._compile (module.js:460:26)
     at Object.Module._extensions..js (module.js:478:10)
     at Module.load (module.js:355:32)
     at Function.Module._load (module.js:310:12)
     at Module.require (module.js:365:17)
     at require (module.js:384:17)
     at accessLog (/app/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:172:19)
     at ExpressEngine.initApp (/app/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:62:17)
     at Dependency.Dependable.runAction (/app/node_modules/meanio/node_modules/lazy-dependable/index.js:73:22)
     at Dependency.runAction (/app/node_modules/meanio/node_modules/lazy-dependable/index.js:98:48)
 Worker 180 died :(

Can somebody give me idea what I made wrong?

**Comment by liorkesos** [comment]
You are OK. This is a bug. Hopefully well address on Sunday/Monday...

**Comment by polinac** [comment]
Thank you! Waiting for the fix.

**Comment by VikramTiwari** [comment]
@polinac If this is still an issue for you, please reopen.
