### ISSUE TITLE
Error: stackSight must user and appId

### ISSUE THREAD

**Issue by darrenwpkd** [linnovate/mean#1190]
I was following the mean.io documentation for Ubuntu 14.04 LTS - and got to the stage where I have to run "gulp" or "node server". Both of which fail with the following:

/redacted/mean/Vouchers/node_modules/mongoose/node_modules/mongodb/lib/server.js:274
      process.nextTick(function() { throw err; })
                                          ^
Error: stackSight must user and appId
    at new StackSight (/redacted/mean/Vouchers/node_modules/stack-sight/index.js:11:46)
    at module.exports (/redacted/mean/Vouchers/node_modules/stack-sight/index.js:51:22)
    at module.exports (/redacted/mean/Vouchers/node_modules/meanio/lib/core_modules/sts/index.js:63:33)
    at ExpressEngine.beginBootstrap (/redacted/mean/Vouchers/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:83:20)
    at Meanio.serveWithDb (/redacted/mean/Vouchers/node_modules/meanio/lib/core_modules/server/index.js:14:10)
    at Consumer.Dependable.runAction (/redacted/mean/Vouchers/node_modules/meanio/node_modules/lazy-dependable/index.js:73:22)
    at Consumer.Dependable.fire (/redacted/mean/Vouchers/node_modules/meanio/node_modules/lazy-dependable/index.js:70:53)
    at Consumer.onResolved (/redacted/mean/Vouchers/node_modules/meanio/node_modules/lazy-dependable/index.js:120:8)
    at Consumer.Dependable.resolve (/redacted/mean/Vouchers/node_modules/meanio/node_modules/lazy-dependable/index.js:56:10)
    at Meanio.Container.notifyResolved (/redacted/mean/Vouchers/node_modules/meanio/node_modules/lazy-dependable/index.js:209:7)
    at Dependency.onResolved (/redacted/mean/Vouchers/node_modules/meanio/node_modules/lazy-dependable/index.js:105:18)
    at Dependency.Dependable.resolve (/redacted/mean/Vouchers/node_modules/meanio/node_modules/lazy-dependable/index.js:56:10)
    at Meanio.Container.register (/redacted/mean/Vouchers/node_modules/meanio/node_modules/lazy-dependable/index.js:167:5)
    at /redacted/mean/Vouchers/node_modules/meanio/lib/core_modules/db/index.js:101:20
    at open (/redacted/mean/Vouchers/node_modules/mongoose/lib/connection.js:484:17)
    at NativeConnection.Connection.onOpen (/redacted/mean/Vouchers/node_modules/mongoose/lib/connection.js:494:5)

**Comment by oritpersik** [comment]
fixed
