### ISSUE TITLE
Submenu error when adding to menus

### ISSUE THREAD

**Issue by hydrotik** [linnovate/mean#1199]
Adding:

```
Socialfeeds.menus.add({
    title: 'Settings',
    roles: ['authenticated'],
    menu: 'main',
    submenus : [
      {
        title: 'Settings',
        link: 'all settings'
      },
      {
        title: 'Create New Settings',
        link: 'create settings'
      },
      {
        'divider': true
      },
      {
        title: 'Filters',
        link: 'all filtering'
      },
      {
        title: 'Create New Filter',
        link: 'create filter'
      }
    ]
  });
```

Gives me the error:

```
TypeError: undefined is not a function
    at get_get (/Users/dadams/Desktop/Node/socialfeeds/node_modules/meanio/lib/menu.js:10:12)
    at Array.map (native)
    at MenuItem.get (/Users/dadams/Desktop/Node/socialfeeds/node_modules/meanio/lib/menu.js:101:30)
    at get_get (/Users/dadams/Desktop/Node/socialfeeds/node_modules/meanio/lib/menu.js:10:12)
    at Array.map (native)
    at MenuItem.get (/Users/dadams/Desktop/Node/socialfeeds/node_modules/meanio/lib/menu.js:101:30)
    at Menus.get (/Users/dadams/Desktop/Node/socialfeeds/node_modules/meanio/lib/menu.js:165:18)
    at /Users/dadams/Desktop/Node/socialfeeds/packages/core/system/server/routes/menus.js:15:30
    at Layer.handle [as handle_request] (/Users/dadams/Desktop/Node/socialfeeds/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/dadams/Desktop/Node/socialfeeds/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/route.js:110:13)
```

It seems the Menu class in npm meanio/lib doesn't work? v 0.7.5

**Comment by hydrotik** [comment]
https://github.com/linnovate/mean/issues/1195
