### ISSUE TITLE
jquery.min.map not found in Production environment

### ISSUE THREAD

**Issue by pbharatprdxn** [linnovate/mean#1200]
Whenever I run the app in production environment I get the following error

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/mnt/app/bower_components/jquery/dist/jquery.min.map'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at module.exports (/home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/bootstrap.js:31:27)
    at /home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/mean.js:20:27
    at Config.onPackageRead (/home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/config.js:104:19)
    at Promise.<anonymous> (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)

When I go and check the the file [jquery.min.map] in the bower_components folder, I always find it and even then I have run bower install and bower cache clean which are the common solutions provided to the problem I am facing but to no success and because of this the app is not deploying on Modulus as well.

In dire need of help guys.

**Comment by liorkesos** [comment]
You're missing "bower install"

On Fri, Jun 5, 2015 at 9:45 AM, pbharatprdxn <notifications@github.com>
wrote:

> Whenever I run the app in production environment I get the following error
>
> fs.js:500
> return binding.open(pathModule._makeLong(path), stringToFlags(flags),
> mode);
> ^
> Error: ENOENT, no such file or directory
> '/mnt/app/bower_components/jquery/dist/jquery.min.map'
> at Error (native)
> at Object.fs.openSync (fs.js:500:18)
> at Object.fs.readFileSync (fs.js:352:15)
> at module.exports
> (/home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/bootstrap.js:31:27)
> at
> /home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/mean.js:20:27
> at Config.onPackageRead
> (/home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/config.js:104:19)
> at Promise.
> (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
> at Promise.emit (events.js:107:17)
> at Promise.emit
> (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
> at Promise.fulfill
> (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
>
> When I go and check the the file [jquery.min.map] in the bower_components
> folder, I always find it and even then I have run bower install and bower
> cache clean which are the common solutions provided to the problem I am
> facing but to no success and because of this the app is not deploying on
> Modulus as well.
>
> In dire need of help guys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1200>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by liorkesos** [comment]
oops  I see you'v allready done that.

On Fri, Jun 5, 2015 at 9:47 AM, Lior Kesos <lior@linnovate.net> wrote:

> You're missing "bower install"
>
> On Fri, Jun 5, 2015 at 9:45 AM, pbharatprdxn <notifications@github.com>
> wrote:
>
>> Whenever I run the app in production environment I get the following error
>>
>> fs.js:500
>> return binding.open(pathModule._makeLong(path), stringToFlags(flags),
>> mode);
>> ^
>> Error: ENOENT, no such file or directory
>> '/mnt/app/bower_components/jquery/dist/jquery.min.map'
>> at Error (native)
>> at Object.fs.openSync (fs.js:500:18)
>> at Object.fs.readFileSync (fs.js:352:15)
>> at module.exports
>> (/home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/bootstrap.js:31:27)
>> at
>> /home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/mean.js:20:27
>> at Config.onPackageRead
>> (/home/prdxn/projects/employee-evaluation-tool/node_modules/meanio/lib/config.js:104:19)
>> at Promise.
>> (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
>> at Promise.emit (events.js:107:17)
>> at Promise.emit
>> (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
>> at Promise.fulfill
>> (/home/prdxn/projects/employee-evaluation-tool/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
>>
>> When I go and check the the file [jquery.min.map] in the bower_components
>> folder, I always find it and even then I have run bower install and bower
>> cache clean which are the common solutions provided to the problem I am
>> facing but to no success and because of this the app is not deploying on
>> Modulus as well.
>>
>> In dire need of help guys.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/linnovate/mean/issues/1200>.
>>
>
>
>
> --
>
> Lior Kesos - http://www.linnovate.net
> Linnovate - Community Infrastructure Care
> mail: lior@linnovate.net
> office: +972 722500881
> cell: +972 524305252
> skype: liorkesos
>
>


-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by RhysJevons** [comment]
I'm having the exact same issue as @pbharatprdxn when deploying to Heroku has anyone got a solution?

Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'
2015-06-18T10:17:04.767355+00:00 app[web.1]:     at Object.fs.readFileSync (fs.js:290:15)
2015-06-18T10:17:04.767356+00:00 app[web.1]:     at module.exports (/app/node_modules/meanio/lib/bootstrap.js:31:27)
2015-06-18T10:17:04.767353+00:00 app[web.1]:     at Object.fs.openSync (fs.js:439:18)
2015-06-18T10:17:04.767358+00:00 app[web.1]:     at /app/node_modules/meanio/lib/mean.js:20:27
2015-06-18T10:17:04.767361+00:00 app[web.1]:     at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
2015-06-18T10:17:04.767359+00:00 app[web.1]:     at Config.onPackageRead (/app/node_modules/meanio/lib/config.js:101:25)
2015-06-18T10:17:04.767365+00:00 app[web.1]:     at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
2015-06-18T10:17:04.767364+00:00 app[web.1]:     at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
2015-06-18T10:17:04.767367+00:00 app[web.1]:     at Object.cb (/app/node_modules/mongoose/lib/query.js:1146:30)
2015-06-18T10:17:04.767368+00:00 app[web.1]: 
2015-06-18T10:17:04.767370+00:00 app[web.1]: fs.js:439
2015-06-18T10:17:04.767362+00:00 app[web.1]:     at Promise.emit (events.js:95:17)
2015-06-18T10:17:04.767372+00:00 app[web.1]:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
2015-06-18T10:17:04.767375+00:00 app[web.1]: Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'
2015-06-18T10:17:04.767376+00:00 app[web.1]:     at Object.fs.openSync (fs.js:439:18)
2015-06-18T10:17:04.767377+00:00 app[web.1]:     at Object.fs.readFileSync (fs.js:290:15)
2015-06-18T10:17:04.767379+00:00 app[web.1]:     at module.exports (/app/node_modules/meanio/lib/bootstrap.js:31:27)
2015-06-18T10:17:04.767384+00:00 app[web.1]:     at Config.onPackageRead (/app/node_modules/meanio/lib/config.js:101:25)

**Comment by pbharatprdxn** [comment]
@RhysJevons My issue was because of my database connection string [Database is hosted on MongoLab], sorting that out made this error go away. Check if its same for you by running the production environment on local machine.

Closing this ticket out since its resolved for me, If you still don't manage to find a solution, feel free to reopen it.

**Comment by RhysJevons** [comment]
@pbharatprdxn  Thanks for the update. I've ran the production environment locally and it works fine. Still seeing this issue in the Heroku logs.
