### ISSUE TITLE
Karma tests failing on clean init

### ISSUE THREAD

**Issue by scfox** [linnovate/mean#1217]
App installs and runs fine after init.  Mocha tests pass. 
But running: npm run karma
Results in 12 failures.

Is this expected behavior?

**Comment by intrepido** [comment]
I get the same error, my enviroment is:
 
- Window 8
- npm 2.10.1
- meanio at latest version: 0.8.74
- mean-cli at latest version: 0.10.12

The error happens when I run in gulp the test task, I get the following in console:

```
gulp test
Invoking gulp - development
[13:03:56] Using gulpfile e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\gulpfile.js
[13:03:56] Starting 'env:test'...
[13:03:56] Finished 'env:test' after 52 μs
[13:03:56] Starting 'karma:unit'...
WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
DEBUG [config]: autoWatch set to false, because of singleRun
DEBUG [plugin]: Loading karma-* from e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-chrome-launcher.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-coffee-preprocessor.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-coverage.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-firefox-launcher.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-html2js-preprocessor.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-jasmine.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-ng-html2js-preprocessor.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-ng-scenario.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-phantomjs-launcher.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-requirejs.
DEBUG [plugin]: Loading plugin e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules/karma-script-launcher.
[13:03:57] Starting 'loadTestSchema'...
[13:03:58] Finished 'loadTestSchema' after 895 ms
[13:03:58] Starting 'mochaTest'...
WARN [watcher]: Pattern "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-jwt/dist/angular-jwt.min.js" does not match any file.


  0 passing (0ms)

[13:03:58] Finished 'mochaTest' after 100 ms
loading docs for: e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\packages\core\articles
Mean app started on port 3001 (test) cluster.worker.id: 0
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/modules.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/admin.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/settings.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/example.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/users.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/themes.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/module-settings.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/modules.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/settings.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/controllers/articles.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/users.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/services/articles.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/controllers/header.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/controllers/index.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/global.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/interceptor.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/menus.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/controllers/meanUser.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/services/meanUser.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/custom/theme/public/controllers/theme.js".
DEBUG [preprocessor.coverage]: Processing "e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/custom/theme/public/services/theme.js".
DEBUG [watcher]: Resolved files:
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/node_modules/jasmine-core/lib/jasmine-core/jasmine.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/node_modules/karma-jasmine/lib/boot.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/node_modules/karma-jasmine/lib/adapter.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/jquery/dist/jquery.min.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular/angular.min.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-mocks/angular-mocks.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-cookies/angular-cookies.min.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-resource/angular-resource.min.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-ui-router/release/angular-ui-router.min.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-bootstrap/ui-bootstrap-tpls.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/web-bootstrap/index.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/system.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/admin.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/example.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/modules.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/settings.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/themes.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/users.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/directives/editable.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/routes/admin.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/module-settings.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/modules.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/settings.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/users.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/controllers/articles.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/routes/articles.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/services/articles.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/tests/articles.spec.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/controllers/header.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/controllers/index.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/routes/system.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/global.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/interceptor.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/menus.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/tests/headers.spec.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/tests/index.spec.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/controllers/meanUser.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/routes/auth.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/services/meanUser.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/tests/auth.spec.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/custom/theme/public/controllers/theme.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/custom/theme/public/routes/theme.js
	e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/custom/theme/public/services/theme.js
INFO [karma]: Karma v0.12.36 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
DEBUG [temp-dir]: Creating temp dir at C:\Users\FIDEL-~1\AppData\Local\Temp\karma-6213489
DEBUG [launcher]: e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\phantomjs\lib\phantom\phantomjs.exe C:\Users\FIDEL-~1\AppData\Local\Temp\karma-6213489/capture.js
DEBUG [web-server]: serving: e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\karma\static/client.html
DEBUG [web-server]: serving: e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/b21-34vQt_ZeDbi2ZF-X
DEBUG [proxy]: NOT upgrading proxyWebSocketRequest /socket.io/1/websocket/b21-34vQt_ZeDbi2ZF-X
DEBUG [karma]: A browser has connected on socket b21-34vQt_ZeDbi2ZF-X
INFO [PhantomJS 1.9.8 (Windows 8 0.0.0)]: Connected on socket b21-34vQt_ZeDbi2ZF-X with id 6213489
DEBUG [launcher]: PhantomJS (id 6213489) captured in 0.81 secs
DEBUG [web-server]: serving: e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\karma\static/context.html
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/node_modules/jasmine-core/lib/jasmine-core/jasmine.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/node_modules/karma-jasmine/lib/boot.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/node_modules/karma-jasmine/lib/adapter.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/jquery/dist/jquery.min.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular/angular.min.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-ui-router/release/angular-ui-router.min.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-mocks/angular-mocks.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-cookies/angular-cookies.min.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-resource/angular-resource.min.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/angular-bootstrap/ui-bootstrap-tpls.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/bower_components/web-bootstrap/index.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/system.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/admin.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/example.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/modules.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/settings.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/themes.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/controllers/users.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/directives/editable.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/routes/admin.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/module-settings.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/modules.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/settings.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/admin/public/services/users.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/controllers/articles.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/routes/articles.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/services/articles.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/articles/public/tests/articles.spec.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/controllers/header.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/controllers/index.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/routes/system.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/global.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/interceptor.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/services/menus.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/tests/headers.spec.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/system/public/tests/index.spec.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/controllers/meanUser.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/routes/auth.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/services/meanUser.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/core/users/public/tests/auth.spec.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/custom/theme/public/controllers/theme.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/custom/theme/public/routes/theme.js
DEBUG [web-server]: serving (cached): e:/Google Drive/Proyectos/JiminyCricket/Codigo/jiminy-mean/packages/custom/theme/public/services/theme.js
DEBUG [proxy]: proxying request - /_getModules to localhost:3000
WARN [proxy]: failed to proxy /_getModules (connect ECONNREFUSED)
WARN [PhantomJS 1.9.8 (Windows 8 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.

DEBUG [karma]: Run complete, exiting.
DEBUG [launcher]: Disconnecting all browsers
DEBUG [launcher]: Process PhantomJS exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\FIDEL-~1\AppData\Local\Temp\karma-6213489
[13:04:16] 'karma:unit' errored after 20 s
[13:04:16] Error: 1
  at formatError (C:\Users\FIDEL-CASA\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
  at Gulp.<anonymous> (C:\Users\FIDEL-CASA\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
  at Gulp.emit (events.js:107:17)
  at Gulp.Orchestrator._emitTaskDone (e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
  at e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\gulp\node_modules\orchestrator\index.js:275:23
  at finish (e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
  at cb (e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
  at removeAllListeners (e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\karma\lib\server.js:218:7)
  at Server.<anonymous> (e:\Google Drive\Proyectos\JiminyCricket\Codigo\jiminy-mean\node_modules\karma\lib\server.js:229:9)
  at Server.g (events.js:199:16)
  at Server.emit (events.js:129:20)
  at net.js:1419:10
  at process._tickDomainCallback (node.js:381:11)
```

**Comment by ariesbrunetyson** [comment]
Any luck with this? I'm also receiving the same error when running karma:unit task.

**Comment by scfox** [comment]
Honestly, after several hours of debugging attempts, I gave up and moved to the mean.js stack.  First attempt came up functioning and all karma and mocha tests passed. For me, if you are committed to BDD, that's table stakes to use any stack or component.

**Comment by lvarayut** [comment]
Did anyone figure it out? I'm facing the same issue.
