### ISSUE TITLE
MeanUserKlass error

### ISSUE THREAD

**Issue by alxpolyakov** [linnovate/mean#1261]
An error occures after reload any url.
at Object.parse (native)
    at MeanUserKlass.onIdentity (http://localhost:3000/users/services/meanUser.js:65:28)
    at Object.fn (http://localhost:3000/users/services/meanUser.js:209:15)
    at n.$get.n.$digest (http://localhost:3000/bower_components/angular/angular.min.js:132:259)
    at n.$get.n.$apply (http://localhost:3000/bower_components/angular/angular.min.js:135:269)
    at l (http://localhost:3000/bower_components/angular/angular.min.js:87:234)
    at F (http://localhost:3000/bower_components/angular/angular.min.js:91:277)
    at XMLHttpRequest.K.onload (http://localhost:3000/bower_components/angular/angular.min.js:92:315)(anonymous function) @ angular.js:12332$get @ angular.js:9111$get.n.$digest @ angular.js:15703$get.n.$apply @ angular.js:15953l @ angular.js:10366F @ angular.js:10538K.onload @ angular.js:10479

**Comment by VikramTiwari** [comment]
@alxpolyakov If this is still an issue for you, please reopen.
