### ISSUE TITLE
Twitter OAuth does not work out of the box (missing dependency)

### ISSUE THREAD

**Issue by dazwin** [linnovate/mean#1264]
After configuring the Twitter consumer key/secret, logging in results in the following error:

```
Error: OAuthStrategy requires session support. Did you forget app.use(express.session(...))?
    at Strategy.OAuthStrategy.authenticate (/vagrant/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:120:41)
    at Strategy.authenticate (/vagrant/node_modules/passport-twitter/lib/strategy.js:85:40)
    at attempt (/vagrant/node_modules/meanio/lib/core_modules/server/node_modules/passport/lib/middleware/authenticate.js:341:16)
...
```

**Comment by dazwin** [comment]
Created PR https://github.com/linnovate/mean/pull/1265
