### ISSUE TITLE
```node server``` failing by project name

### ISSUE THREAD

**Issue by computerlyrik** [linnovate/mean#1283]
```
mean init modelfoo
```

works:

```
npm install
```

does not work:

```
node server
```

``` bash

/home/cf/metamodel/node_modules/meanio/node_modules/q/q.js:155
                throw e;
                      ^
MissingSchemaError: Schema hasn't been registered for model "Circle".
Use mongoose.model(name, schema)
    at Mongoose.model (/home/cf/tmp/metamodel/node_modules/mongoose/lib/index.js:329:13)
    at Object.<anonymous> (/home/cf/tmp/metamodel/packages/core/circles/server/controllers/circles.js:2:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireModel (/home/cf/tmp/metamodel/node_modules/meanio/lib/core_modules/module/index.js:146:15)
    at /home/cf/tmp/metamodel/node_modules/meanio/lib/core_modules/module/util.js:21:7
    at Array.forEach (native)
    at walk (/home/cf/tmp/metamodel/node_modules/meanio/lib/core_modules/module/util.js:16:25)
    at /home/cf/tmp/metamodel/node_modules/meanio/lib/core_modules/module/util.js:23:7
    at Array.forEach (native)
    at Object.walk (/home/cf/tmp/metamodel/node_modules/meanio/lib/core_modules/module/util.js:16:25)
    at new Module (/home/cf/tmp/metamodel/node_modules/meanio/lib/core_modules/module/index.js:162:10)
    at Object.<anonymous> (/home/cf/tmp/metamodel/packages/core/circles/app.js:10:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

sometimes it states
MissingSchemaError: Schema hasn't been registered for model "User".

Seems to fail everytime the string "model" is in the parent directory

**Comment by VikramTiwari** [comment]
@computerlyrik If this is still an issue for you, please reopen.

**Comment by rjVapes** [comment]
Issue still exists.  If the directory structure has 'model' in it, this error occurs.  Probably an issue in the directory walking for model pre-loading.

**Comment by bshenk** [comment]
Renaming folder title from "model"/"models" fixed the issue for me.
