### ISSUE TITLE
Required module in clean production installation

### ISSUE THREAD

**Issue by CVex2150J** [linnovate/mean#1310]
Sorry for my english.
In the main Package.JSON at line 54 is the requirement for "connect-modrewrite": "latest".
This requirement is in "dev" only, so if you send the server in production (npm install --production) modrewrite should not exist at all.

```
Error: Cannot find module 'connect-modrewrite'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ( **********mean\config\express.js:14:16)
```

**Comment by CVex2150J** [comment]
I've tested the master branch at 18/08/15@11:15am my first post is not a problem anymore.
But this one is.
In v0.5.5 After deactivating connect-modwrite in production and/or by moving the requirement in the production dependencies another missing module is appearing in the install log.

The same error appeared in the master branch

the error in i8ln package is one of the 4 errors( package not found, admin, il8n, users)
```
> i18n@0.0.1 postinstall **********\mean\packages\custom\i18n
> bower install

module.js:338
    throw err;
          ^
Error: Cannot find module 'through'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (**********\mean\node_modules\bower\node_modules\inquirer\lib\ui\bottom-bar.js:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
Error: npm install failed
{ [Error: i18n@0.0.1 postinstall: `bower install`
Exit status 1]
  code: 'ELIFECYCLE',
  pkgid: 'i18n@0.0.1',
  stage: 'postinstall',
  script: 'bower install',
  pkgname: 'i18n' }
```

**Comment by CVex2150J** [comment]
I've check the inquirer module and the dependencies ""through": "~2.3.4"" is in the package.json... 
So there is a probleme with the npm shrinkwrap. It needs to be updated

**Comment by CVex2150J** [comment]
Also, I want to know why there is phantomjs and jasmine-core in the shrinkwrap.json. These librairies are for testing no ?!?! So there should be in the devdependencies?!
Oh, and theses 2 librairies are not in the package.json.

So npm shrinkwrap does want to update went using to command.
```
**********\mean>npm shrinkwrap
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\Program Files\\nodejs\\\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: jasmine-core@2.3.4 **********\mean\node_modules\jasmine-core
npm ERR! extraneous: phantomjs@1.9.18 **********\mean\node_modules\phantomjs
```
