### ISSUE TITLE
Cannot find module 'swagger-node-express'

### ISSUE THREAD

**Issue by JereMc** [linnovate/mean#1334]
Working on a virtualbox Ubuntu server.   Installed MEAN stack following instructions in the Readme file, here.  Tried to run gulp and got this:

Invoking gulp - development
[01:41:50] Using gulpfile /var/www/jammeantest/gulpfile.js
[01:41:50] Starting 'clean'...
[01:41:50] Finished 'clean' after 4.81 ms
[01:41:50] Starting 'default'...
[01:41:50] Starting 'coffee'...
[01:41:50] Finished 'coffee' after 11 ms
[01:41:50] Starting 'clean'...
[01:41:50] Starting 'less'...
[01:41:50] Starting 'csslint'...
[01:41:51] Starting 'env:development'...
[01:41:51] Finished 'env:development' after 21 μs
[01:41:51] Starting 'devServe'...
[01:41:51] Finished 'devServe' after 613 ms
[01:41:51] Starting 'watch'...
[01:41:54] Finished 'watch' after 2.29 s
[01:41:54] Finished 'clean' after 3.64 s
[01:41:54] [nodemon] v1.4.1
[01:41:54] [nodemon] to restart at any time, enter `rs`
[01:41:54] [nodemon] watching: *.*
[01:41:54] [nodemon] starting `node --debug server.js`
debugger listening on port 5858
[01:41:54] Finished 'less' after 3.82 s
[01:41:54] 
[01:41:54] csslint: 3 files lint free
[01:41:54] Finished 'csslint' after 3.74 s
[01:41:54] Starting 'development'...
[01:41:54] Finished 'development' after 12 μs
/var/www/jammeantest/packages/core/users/public/assets/lib/angular-jwt/dist/angular-jwt.min.js not found
/var/www/jammeantest/packages/core/admin/public/assets/lib/ng-clip/src/ngClip.js not found
/var/www/jammeantest/packages/core/admin/public/assets/lib/zeroclipboard/dist/ZeroClipboard.js not found

/var/www/jammeantest/node_modules/meanio/node_modules/q/q.js:155
                throw e;
                      ^
Error: Cannot find module 'swagger-node-express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /var/www/jammeantest/packages/core/swagger/app.js:14:13
    at Dependency.Dependable.runAction (/var/www/jammeantest/node_modules/meanio/node_modules/lazy-dependable/index.js:73:22)
    at Dependency.runAction (/var/www/jammeantest/node_modules/meanio/node_modules/lazy-dependable/index.js:98:48)
    at Dependency.Dependable.fire (/var/www/jammeantest/node_modules/meanio/node_modules/lazy-dependable/index.js:70:53)
    at Dependency.fire (/var/www/jammeantest/node_modules/meanio/node_modules/lazy-dependable/index.js:93:38)
    at Consumer.Dependable.tryResolve (/var/www/jammeantest/node_modules/meanio/node_modules/lazy-dependable/index.js:67:24)
    at traverseArrayConditionally (/var/www/jammeantest/node_modules/meanio/node_modules/lazy-dependable/index.js:20:11)
    at Consumer.Dependable.resolve (/var/www/jammeantest/node_modules/meanio/node_modules/lazy-dependable/index.js:50:3)
    at Meanio.Container.resolve (/var/www/jammeantest/node_modules/meanio/node_modules/lazy-dependable/index.js:195:5)
    at moduleActivator (/var/www/jammeantest/node_modules/meanio/lib/core_modules/module/index.js:81:21)
    at ListItem.apply (/var/www/jammeantest/node_modules/meanio/node_modules/complex-list/index.js:22:12)
    at ModuleList.List.traverse (/var/www/jammeantest/node_modules/meanio/node_modules/complex-list/index.js:134:10)
    at enableModules (/var/www/jammeantest/node_modules/meanio/lib/core_modules/module/index.js:101:12)
    at findModulesDone (/var/www/jammeantest/node_modules/meanio/lib/core_modules/module/index.js:69:3)
    at _fulfilled (/var/www/jammeantest/node_modules/meanio/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/var/www/jammeantest/node_modules/meanio/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/var/www/jammeantest/node_modules/meanio/node_modules/q/q.js:796:13)
    at /var/www/jammeantest/node_modules/meanio/node_modules/q/q.js:604:44
    at runSingle (/var/www/jammeantest/node_modules/meanio/node_modules/q/q.js:137:13)
    at flush (/var/www/jammeantest/node_modules/meanio/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:415:13)
[01:42:06] [nodemon] app crashed - waiting for file changes before starting...

**Comment by iolufemi** [comment]
Do this

```sh
$ npm install --save swagger-node-express
```

**Comment by adskjohn** [comment]
This should be installed by /packages/core/swagger/package.json.  You shouldn't need to add package dependencies to your top level package.json.  If the npm install is not cascading properly your post-install script might not have been run.  Try `npm install` again, and if you still have the same issue explicitly run the post-install script via `node tools/scripts/postinstall.js` and see if that will run it for you and where it gets you.

**Comment by lavaldi** [comment]
I solved this with the issue #1313 : run `bower install` in the root folder and then run `npm install` again :+1:
