### ISSUE TITLE
npm install fails (warning with json-file-plus and errors with node-gyp) 

### ISSUE THREAD

**Issue by Thomas087** [linnovate/mean#1341]
Hi all,

My npm install fails. I tried everything suggested related to the errors on stackoverflow, including completely reinstalling node and npm (running latest versions) and node-gyp, but to no avail.

The output is the following:

sudo npm install -g mean-cli

> mean-cli@0.10.14 preinstall /usr/local/lib/node_modules/mean-cli
> node ./scripts/preinstall

npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be propagated
 
> mean-health@0.1.7 postinstall /usr/local/lib/node_modules/mean-cli/node_modules/mean-health
> node ./postinstall.js

 
> kerberos@0.0.12 install /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
\
> bson-ext@0.1.12 install /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o
In file included from ../ext/bson.cc:36:
In file included from ../ext/bson.h:17:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: 
      candidate function not viable: 2nd argument ('const char *') would lose
      const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: 
      candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: 
      candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../ext/bson.cc:36:
In file included from ../ext/bson.h:17:
../node_modules/nan/nan.h:676:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'const
      v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&'
      for 1st argument
class Local {
      ^
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate
      template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate
      template ignored: could not match 'S *' against
      'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../ext/bson.cc:36:
In file included from ../ext/bson.h:17:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../ext/bson.cc:14:
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning
      to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded
      from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../ext/bson.cc:14:
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning
      to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded
      from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../ext/bson.cc:14:
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning
      to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded
      from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../ext/bson.cc:14:
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning
      to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/thomasgraziani/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded
      from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/bson/ext/bson.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release/bson.node" "--module_name=bson" "--module_path=/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release"
gyp ERR! cwd /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 13.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
node-pre-gyp ERR! node -v v4.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release' (1)
  CXX(target) Release/obj.target/bson/ext/bson.o
/usr/local/bin/mean -> /usr/local/lib/node_modules/mean-cli/bin/mean
/usr/local/bin/mean-init -> /usr/local/lib/node_modules/mean-cli/bin/mean-init
/usr/local/bin/mean-authorize -> /usr/local/lib/node_modules/mean-cli/bin/mean-authorize
/usr/local/bin/mean-addKey -> /usr/local/lib/node_modules/mean-cli/bin/mean-addKey
/usr/local/bin/mean-search -> /usr/local/lib/node_modules/mean-cli/bin/mean-search
/usr/local/bin/mean-deploy -> /usr/local/lib/node_modules/mean-cli/bin/mean-deploy
/usr/local/bin/mean-logs -> /usr/local/lib/node_modules/mean-cli/bin/mean-logs
/usr/local/bin/mean-whoami -> /usr/local/lib/node_modules/mean-cli/bin/mean-whoami
/usr/local/bin/mean-postinstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-postinstall
/usr/local/bin/mean-install -> /usr/local/lib/node_modules/mean-cli/bin/mean-install
/usr/local/bin/mean-register -> /usr/local/lib/node_modules/mean-cli/bin/mean-register
/usr/local/bin/mean-login -> /usr/local/lib/node_modules/mean-cli/bin/mean-login
/usr/local/bin/mean-publish -> /usr/local/lib/node_modules/mean-cli/bin/mean-publish
/usr/local/bin/mean-docs -> /usr/local/lib/node_modules/mean-cli/bin/mean-docs
/usr/local/bin/mean-logout -> /usr/local/lib/node_modules/mean-cli/bin/mean-logout
/usr/local/bin/mean-disable -> /usr/local/lib/node_modules/mean-cli/bin/mean-disable
/usr/local/bin/mean-status -> /usr/local/lib/node_modules/mean-cli/bin/mean-status
/usr/local/bin/mean-uninstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-uninstall
/usr/local/bin/mean-preinstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-preinstall
/usr/local/bin/mean-list -> /usr/local/lib/node_modules/mean-cli/bin/mean-list
/usr/local/bin/mean-package -> /usr/local/lib/node_modules/mean-cli/bin/mean-package
/usr/local/bin/mean-enable -> /usr/local/lib/node_modules/mean-cli/bin/mean-enable
/usr/local/bin/mean-user -> /usr/local/lib/node_modules/mean-cli/bin/mean-user
mean-cli@0.10.14 /usr/local/lib/node_modules/mean-cli
├── opener@1.4.1
├── async-series@0.0.1
├── progress@1.1.8
├── crypto@0.0.3
├── shelljs@0.3.0
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── mean-health@0.1.7
├── lodash@2.4.2
├── json-file-plus@2.0.0 (is@2.0.2, node.extend@1.1.5, promiseback@2.0.1)
├── prompt@0.2.14 (revalidator@0.1.8, read@1.0.7, pkginfo@0.3.0, winston@0.8.3, utile@0.2.1)
├── request@2.61.0 (aws-sign2@0.5.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, oauth-sign@0.8.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@4.0.0, combined-stream@1.0.5, form-data@1.0.0-rc3, mime-types@2.1.6, http-signature@0.11.0, bl@1.0.0, tough-cookie@2.0.0, hawk@3.1.0, har-validator@1.8.0)
├── inquirer@0.8.5 (figures@1.3.5, ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.8, chalk@1.1.1, readline2@0.1.1, lodash@3.10.1, rx@2.5.3)
├── bower@1.5.2 (is-root@1.0.0, junk@1.0.2, stringify-object@1.0.1, user-home@1.1.1, chmodr@0.1.0, abbrev@1.0.7, archy@1.0.0, opn@1.0.2, bower-logger@0.2.2, bower-endpoint-parser@0.2.2, graceful-fs@3.0.8, lockfile@1.0.1, lru-cache@2.7.0, nopt@3.0.4, retry@0.6.1, tmp@0.0.24, q@1.4.1, request-progress@0.3.1, chalk@1.1.1, promptly@0.2.0, semver@2.3.2, bower-json@0.4.0, shell-quote@1.4.3, which@1.1.2, p-throttler@0.1.1, fstream@1.0.8, mkdirp@0.5.0, fstream-ignore@1.0.2, glob@4.5.3, rimraf@2.4.3, insight@0.5.3, tar-fs@1.8.1, decompress-zip@0.1.0, update-notifier@0.3.2, request@2.53.0, github@0.2.4, bower-registry-client@0.3.0, cardinal@0.4.4, deep-sort-object@0.1.1, mout@0.11.0, bower-config@0.6.1, configstore@0.3.2, inquirer@0.8.0, handlebars@2.0.0)
├── npm@2.14.3
└── mongoose@4.0.8 (regexp-clone@0.0.1, sliced@0.0.5, muri@1.0.0, hooks-fixed@1.0.2, mpromise@0.5.4, kareem@1.0.1, mpath@0.1.1, async@0.9.0, ms@0.1.0, mquery@1.6.1, mongodb@2.0.34, bson@0.3.2)

**Comment by anstaendig** [comment]
I got the exact same issue. Maybe it's because of the v4 of node?

**Comment by berendvaneerde** [comment]
+1

**Comment by VikramTiwari** [comment]
It is because of v4. The `nan` package is still not fully supported by v4 cause its stuck with `bson-ext` package. Deep down dependencies. :(

**Comment by cklanac** [comment]
I encountered the same issue... pretty easy to fix by downgrading Node.js v0.12. I'm using homebrew so I did the following

```
MacBookPro ~/Developer$ brew unlink node
Unlinking /usr/local/Cellar/node/4.1.1... 9 symlinks removed

MacBookPro ~/Developer$ brew search node
leafnode	   node (installed)   nodebrew		 nodenv
homebrew/versions/node010	  homebrew/versions/node06	    Caskroom/cask/node-profiler	      Caskroom/cask/nodeclipse
homebrew/versions/node012	  homebrew/versions/node08	    Caskroom/cask/node		      Caskroom/cask/soundnode
homebrew/versions/node04	  Caskroom/cask/mindnode-pro	    Caskroom/cask/nodebox

MacBookPro ~/Developer$ brew install homebrew/versions/node012
==> Installing node012 from homebrew/homebrew-versions
==> Downloading https://homebrew.bintray.com/bottles-versions/node012-0.12.7.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring node012-0.12.7.yosemite.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node012/0.12.7: 2698 files, 30M

MacBookPro ~/Developer/meanio$ node --version
v0.12.7
```

Then install and init worked fine...
```
MacBookPro ~/Developer$ npm install -g mean-cli
MacBookPro ~/Developer$ mean init MyApp
```

**Comment by mklybor** [comment]
I am getting similar (but not exact) errors trying to install mean-cli. I have v3.3.1 of io.js. I am trying to install on windows. I have python 2.7 and the latest vc++.

the first errors to come up are:

c:\users\klybor\.node-gyp\iojs-3.3.1\include\node\v8.h(336): error C2988: unrecognizable template declaration/definition [C:\Users\klybor\AppData\Roaming\npm\node_modules\mean-cli\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\kerberos.vcxproj]
c:\users\klybor\.node-gyp\iojs-3.3.1\include\node\v8.h(336): error C2988: unrecognizable template declaration/definition [C:\Users\klybor\AppData\Roaming\npm\node_modules\mean-cli\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\kerberos.vcxproj]
c:\users\klybor\.node-gyp\iojs-3.3.1\include\node\v8.h(336): error C2988: unrecognizable template declaration/definition [C:\Users\klybor\AppData\Roaming\npm\node_modules\mean-cli\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\kerberos.vcxproj]


....

and eventually

C:\Users\klybor\.node-gyp\iojs-3.3.1\include\node\v8.h(3218): fatal error C1003: error count exceeds 100; stopping compilation [C:\Users\klybor\AppData\Roaming\npm\node_modules\mean-cli\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]

I assume that this means failure?

**Comment by z3dmax** [comment]
Try to update your node to the last version...I had the same problem with the old v4.1.1 and now it 's gone with the v4.1.2

**Comment by Lewiscowles1986** [comment]
I Have this issue with node 4.1.2 on Debian Jessie, compiled from source as per node website guidelines, with intl support.

for me it means I cannot play with MEAN until it's updated, as being crippled to an old version of node seems like the worse end of a trade-off

**Comment by Lewiscowles1986** [comment]
Right so even though mean still shows me an error, it is now a lot less verbose after running the following...

```SHELL
sudo npm update -g npm
sudo npm install -g grunt
sudo npm install -g grunt-cli
sudo npm install -g bower
sudo npm update -g grunt
sudo npm update -g grunt-cli
sudo npm update -g bower
sudo npm install -g mean-cli
```

Also mean-cli seems to be installed, although I have no idea if the failed kerberos module will affect anything (I don't knowingly use kerberos anyway)

**console output**

```
sudo npm install -g mean-cli
npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be propagated
npm WARN lifecycle mean-cli@0.10.14~preinstall: cannot run in wd %s %s (wd=%s) mean-cli@0.10.14 node ./scripts/preinstall /usr/local/lib/node_modules/.staging/mean-cli-2db3416b5b1ebe281952b19cb09e6e2f
/usr/local/bin/mean -> /usr/local/lib/node_modules/mean-cli/bin/mean
/usr/local/bin/mean-init -> /usr/local/lib/node_modules/mean-cli/bin/mean-init
/usr/local/bin/mean-authorize -> /usr/local/lib/node_modules/mean-cli/bin/mean-authorize
/usr/local/bin/mean-whoami -> /usr/local/lib/node_modules/mean-cli/bin/mean-whoami
/usr/local/bin/mean-login -> /usr/local/lib/node_modules/mean-cli/bin/mean-login
/usr/local/bin/mean-addKey -> /usr/local/lib/node_modules/mean-cli/bin/mean-addKey
/usr/local/bin/mean-publish -> /usr/local/lib/node_modules/mean-cli/bin/mean-publish
/usr/local/bin/mean-search -> /usr/local/lib/node_modules/mean-cli/bin/mean-search
/usr/local/bin/mean-deploy -> /usr/local/lib/node_modules/mean-cli/bin/mean-deploy
/usr/local/bin/mean-logs -> /usr/local/lib/node_modules/mean-cli/bin/mean-logs
/usr/local/bin/mean-register -> /usr/local/lib/node_modules/mean-cli/bin/mean-register
/usr/local/bin/mean-postinstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-postinstall
/usr/local/bin/mean-preinstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-preinstall
/usr/local/bin/mean-install -> /usr/local/lib/node_modules/mean-cli/bin/mean-install
/usr/local/bin/mean-uninstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-uninstall
/usr/local/bin/mean-docs -> /usr/local/lib/node_modules/mean-cli/bin/mean-docs
/usr/local/bin/mean-package -> /usr/local/lib/node_modules/mean-cli/bin/mean-package
/usr/local/bin/mean-list -> /usr/local/lib/node_modules/mean-cli/bin/mean-list
/usr/local/bin/mean-status -> /usr/local/lib/node_modules/mean-cli/bin/mean-status
/usr/local/bin/mean-user -> /usr/local/lib/node_modules/mean-cli/bin/mean-user
/usr/local/bin/mean-logout -> /usr/local/lib/node_modules/mean-cli/bin/mean-logout
/usr/local/bin/mean-disable -> /usr/local/lib/node_modules/mean-cli/bin/mean-disable
/usr/local/bin/mean-enable -> /usr/local/lib/node_modules/mean-cli/bin/mean-enable

> kerberos@0.0.15 install /usr/local/lib/node_modules/mean-cli/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.1.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/mean-cli/node_modules/kerberos/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/mean-cli/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/mean-cli/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mean-cli/node_modules/kerberos
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bson-ext@0.1.13 install /usr/local/lib/node_modules/mean-cli/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/local/lib/node_modules/mean-cli/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory '/usr/local/lib/node_modules/mean-cli/node_modules/bson-ext/build'

> mean-health@0.1.7 postinstall /usr/local/lib/node_modules/mean-cli/node_modules/mean-health
> node ./postinstall.js



vagrant@debian-jessie:~$ mean

  Usage: mean [options] [command]


  Commands:

    init <name> [options]       Create a MEAN application in the current working directory
    postinstall                 Run bower and npm install for packages
    preinstall                  Install dependencies from mean.json
    install <module> [options]  Installs a MEAN module
    uninstall <module>          Uninstalls a MEAN module
    docs                        Opens MEAN documentation in your local browser
    package <name> [options]    package
    deploy                      Deploys an app to the mean cloud
    logs                        Receives logs from app deployed in cloud.mean.io
    list                        List all installed packages
    status                      Overall system status
    user <email> [options]      Manage users
    authorize                   Authorize your client
    logout                      Logout authorized client
    login                       Login to the network and authorized client
    whoami                      Identifies authorized user
    register                    Registers a user on mean network
    addKey                      Add SSH key to network.mean.io
    publish                     Publishes a package on the mean network
    search                      Searches for a package on the mean network
    disable <name>              disable user reporting
    enable <name>               enable user reporting
    help [cmd]                  display help for [cmd]

  Options:

    -h, --help     output usage information
    -v, --version  output the version number
    --env [env]    Mean environment defaults to `development`

vagrant@debian-jessie:~$ mean -v
0.10.14
vagrant@debian-jessie:~$ mean status
Invalid MEAN app or not in app root
vagrant@debian-jessie:~$
```

**Comment by Lewiscowles1986** [comment]
Also worth noting is that this is mean-cli... mean is a completely separate repo... (apologies to MEAN stack devs)

**Comment by VikramTiwari** [comment]
Please open the issue in mean-cli project.
