### ISSUE TITLE
Cannot push to heroku : bufferutil@1.1.0 Failed to exec install script

### ISSUE THREAD

**Issue by mmind-hub** [linnovate/mean#1352]
Hi,

I cannot push my project anymore to heroku, it looks like bufferutil is a karma depedency.
I tried rolling back to the previous version of karma without any success.

Does anyone has a solution ? 
I'm stuck and cannot push my project for my client.

Thanks a lot in advance ! 

Here are my heroku logs :
remote: 21752 info install bufferutil@1.1.0
remote: 21753 verbose unsafe-perm in lifecycle true
remote: 21754 info bufferutil@1.1.0 Failed to exec install script
remote: 21755 verbose stack Error: bufferutil@1.1.0 install: `node-gyp rebuild`
remote: 21755 verbose stack Exit status 1
remote: 21755 verbose stack     at EventEmitter.<anonymous> (/tmp/build_f6a301b9f0c6a7f8b992ffc6d11e6ef4/vendor/node/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
remote: 21755 verbose stack     at emitTwo (events.js:87:13)
remote: 21755 verbose stack     at EventEmitter.emit (events.js:172:7)
remote: 21755 verbose stack     at ChildProcess.<anonymous> (/tmp/build_f6a301b9f0c6a7f8b992ffc6d11e6ef4/vendor/node/lib/node_modules/npm/lib/utils/spawn.js:24:14)
remote: 21755 verbose stack     at emitTwo (events.js:87:13)
remote: 21755 verbose stack     at ChildProcess.emit (events.js:172:7)
remote: 21755 verbose stack     at maybeClose (internal/child_process.js:817:16)
remote: 21755 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
remote: 21756 verbose pkgid bufferutil@1.1.0
remote: 21757 verbose cwd /tmp/build_f6a301b9f0c6a7f8b992ffc6d11e6ef4
remote: 21758 error Linux 3.13.0-61-generic
remote: 21759 error argv "/tmp/build_f6a301b9f0c6a7f8b992ffc6d11e6ef4/vendor/node/bin/node" "/tmp/build_f6a301b9f0c6a7f8b992ffc6d11e6ef4/vendor/node/bin/npm" "rebuild"
remote: 21760 error node v4.1.1
remote: 21761 error npm  v2.14.4
remote: 21762 error code ELIFECYCLE
remote: 21763 error bufferutil@1.1.0 install: `node-gyp rebuild`
remote: 21763 error Exit status 1
remote: 21764 error Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
remote: 21764 error This is most likely a problem with the bufferutil package,
remote: 21764 error not with npm itself.
remote: 21764 error Tell the author that this fails on your system:
remote: 21764 error     node-gyp rebuild
remote: 21764 error You can get their info via:
remote: 21764 error     npm owner ls bufferutil
remote: 21764 error There is likely additional logging output above.
remote: 21765 verbose exit [ 1, true ]
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:

**Comment by mmind-hub** [comment]
found it !
it was a cache problem :  heroku repo:purge_cache -a myapp
