### ISSUE TITLE
Error: Cannot find module 'express-validator'

### ISSUE THREAD

**Issue by CrookedGrin** [linnovate/mean#1358]
Just installed today, following the instructions on Github. Everything seemed to install OK. However, when I run gulp, I'm seeing the following:

/Users/udarom1/cg/crookedgrin.com/node_modules/mongoose/node_modules/mongodb/lib/server.js:274
      process.nextTick(function() { throw err; })
                                    ^

Error: Cannot find module 'express-validator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/udarom1/cg/crookedgrin.com/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:3:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.ServerEngine.produceEngine (/Users/udarom1/cg/crookedgrin.com/node_modules/meanio/lib/core_modules/server/engine.js:16:21)
    at Meanio.serveWithDb (/Users/udarom1/cg/crookedgrin.com/node_modules/meanio/lib/core_modules/server/index.js:13:29)
    at Consumer.Dependable.runAction (/Users/udarom1/cg/crookedgrin.com/node_modules/meanio/node_modules/lazy-dependable/index.js:73:22)
    at Consumer.Dependable.fire (/Users/udarom1/cg/crookedgrin.com/node_modules/meanio/node_modules/lazy-dependable/index.js:70:53)
    at Consumer.onResolved (/Users/udarom1/cg/crookedgrin.com/node_modules/meanio/node_modules/lazy-dependable/index.js:120:8)
[16:26:50] [nodemon] app crashed - waiting for file changes before starting...

Any ideas as to what's going on?

**Comment by claustres** [comment]
Don't know why but it seems that a required node module hasn't been installed, try to make `npm install` again or do it manually `npm install express-validator`

**Comment by ashblue** [comment]
I had to re-install node.js on top of manually installing the express-validator.

**Comment by puttyman** [comment]
I was able to replicate this issue. I believe its with node 5.0 where you have to run npm install a few times to make sure it installed all deps. However on 0.10 a single npm install works just fine.

**Comment by timelf123** [comment]
I am able to replicate with node 4.2.2. Fix was to re-run npm install a few times. Or manually `npm install express-validator`

**Comment by rjVapes** [comment]
What version of npm are people using here?  Our tests run multiple variations on node/npm versions and I've only noticed npm install failures on node 0.10/0.12 with npm 1.x (node 4+ and npm 2+ haven't caused any failures that I've noticed)

**Comment by timelf123** [comment]
Npm v2.14.7

I can't replicate every time which is weird. On a fresh `mean init` I didn't have this problem

**Comment by amirmog** [comment]
Had the same issue, and npm install didn't solve it. had to manually  ``` npm install express-validator ``` and some more modules like ``` passport ```.

**Comment by timelf123** [comment]
We updated the shrinkwrap file today which hopefully solves this problem for npm < 3.0. Does anyone still have this issue after pulling upstream/master?

**Comment by htamagnus** [comment]
sometimes it may be the version the package is at. take a look at this.
