### ISSUE TITLE
Getting SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by jianweichuah** [linnovate/mean#1389]
Ran: 
$ sudo npm install -g mean-cli 
$ mean
/usr/local/lib/node_modules/mean-cli/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Http = require('http');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mean-cli/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by johnwalshuk** [comment]
+1

**Comment by mcorbridge** [comment]
I would love to get this answered as well
+1

**Comment by VikramTiwari** [comment]
Sadly this is not a bug in MEAN or `mean-cli`.
On looking at the error directory
`/usr/local/lib/node_modules/mean-cli/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5`

The error path is `boom -> hawk -> request -> mean-cli -> mean`
While this is being flagged as an error by compiler, it is not so. (http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode)

All the packages are moving towards ES6 and this will be common occurrence until all the ES6 standards are available in nodejs. Until then I would recommend using `--harmony` flag while running the programs.

**Comment by jianweichuah** [comment]
$ mean --harmony init project

/usr/local/lib/node_modules/mean-cli/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Http = require('http');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mean-cli/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

I can even run "mean --help".
How do I get around this?

**Comment by jianweichuah** [comment]
Updating Node version:
```
# npm cache clean -f
# npm install -g n
# n stable
```

Then reinstall mean-cli
```
sudo npm install -g mean-cli
```

Solves the problem for me.

**Comment by VikramTiwari** [comment]
@jianweichuah Can you provide node version you were earlier at?

**Comment by jianweichuah** [comment]
@VikramTiwari It was v0.10.13
After the update it's v5.0.0
