### ISSUE TITLE
Need a password for git.mean.io repo

### ISSUE THREAD

**Issue by dillinger** [linnovate/mean#1396]
After executing `mean postinstall` command, asking password for this repo https://git.mean.io/Vikram/bootstrap.git.

Could you help me with this?

```bash
Installing module: bootstrap:
git clone --branch master https://git.mean.io/Vikram/bootstrap.git packages/contrib/bootstrap
Installing module: bootstrap:
git clone --branch master https://git.mean.io/Vikram/bootstrap.git packages/contrib/bootstrap
Package not found.
Package not found.
Package not found.
Package not found.
Installing module: bootstrap:
git clone --branch master https://git.mean.io/Vikram/bootstrap.git packages/contrib/bootstrap
Installing module: bootstrap:
git clone --branch master https://git.mean.io/Vikram/bootstrap.git packages/contrib/bootstrap
Installing module: bootstrap:
shell.js: internal error

Error: ENOENT, no such file or directory 'packages/contrib/bootstrap/.git/config.lock'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at rmdirSyncRecursive (/usr/lib/node_modules/mean-cli/node_modules/shelljs/src/rm.js:20:23)
    at rmdirSyncRecursive (/usr/lib/node_modules/mean-cli/node_modules/shelljs/src/rm.js:23:7)
    at /usr/lib/node_modules/mean-cli/node_modules/shelljs/src/rm.js:141:7
    at Array.forEach (native)
    at Object._rm (/usr/lib/node_modules/mean-cli/node_modules/shelljs/src/rm.js:105:9)
    at Object.rm (/usr/lib/node_modules/mean-cli/node_modules/shelljs/src/common.js:186:23)
    at /usr/lib/node_modules/mean-cli/lib/cli.js:670:15
    at Request._callback (/usr/lib/node_modules/mean-cli/lib/cli.js:627:28)

**Comment by VikramTiwari** [comment]
Hey @dillinger This should not be happening. Did you tried installing `bootstrap` as a MEAN package?
Bootstrap is the default theme for MEAN and comes pre-installed. You don't need to install it on top.

**Comment by dillinger** [comment]
Hi @VikramTiwari,
Sorry for the late reply. I solve this problem by removing my packages folder and clean up the cache of npm and install all from the scratch.

**Comment by VikramTiwari** [comment]
Nice. :)
