### ISSUE TITLE
Getting Authorization error

### ISSUE THREAD

**Issue by shreyasubale** [linnovate/mean#1406]
I get this error ( just installed and trying to run mean ) 

UnauthorizedError: Format is Authorization: Bearer [token]
    at middleware (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/node_modules/express-jwt/lib/index.js:70:23)
    at Layer.handle [as handle_request] (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:312:13)
    at /Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:271:10)
    at methodOverride (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/method-override/index.js:58:5)
    at Layer.handle [as handle_request] (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:312:13)
    at /Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:271:10)
    at /Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express-validator/lib/express_validator.js:228:5
    at Layer.handle [as handle_request] (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:312:13)
    at /Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/cookie-parser/index.js:68:5)
    at Layer.handle [as handle_request] (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:312:13)
    at /Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:271:10)
    at /Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:40:5
    at Layer.handle [as handle_request] (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:312:13)
    at /Users/shreyas.ubale/projects/beerhug/beerhug/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:280:7

**Comment by shreyasubale** [comment]
Found the issue - it was due to chrome remembering the basic http creds of a app which was running on same port and url. Clearing which  fixed it.
