### ISSUE TITLE
Heroku deploy issues

### ISSUE THREAD

**Issue by timelf123** [linnovate/mean#1409]
```
 npm ERR! enoent ENOENT: no such file or directory, rename 'node_modules/meanio/node_modules/express-jwt/node_modules/jsonwebtoken/node_modules/jws/node_modules/base64url/node_modules/concat-stream/node_modules/inherits' -> 'node_modules/inherits'
```
Looks like npm is choking on installing all the deps. Not sure if it's a shrinkwrap issue or an npm install issue

```
remote: -----> Building dependencies
remote:        npm ERR! Linux 3.13.0-66-generic
remote:        npm ERR! argv "/tmp/build_462c2f46476404829614cb25ce2bf6ab/.heroku/node/bin/node" "/tmp/build_462c2f46476404829614cb25ce2bf6ab/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_462c2f46476404829614cb25ce2bf6ab/.npmrc"
remote:        npm ERR! node v5.0.0
remote:        npm ERR! npm  v3.3.6
remote:        npm ERR! path /tmp/build_462c2f46476404829614cb25ce2bf6ab/node_modules/meanio/node_modules/express-jwt/node_modules/jsonwebtoken/node_modules/jws/node_modules/base64url/node_modules/concat-stream/node_modules/inherits
remote:        npm ERR! code ENOENT
remote:        npm ERR! errno -2
remote:        npm ERR! syscall rename
remote:        
remote:        npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/build_462c2f46476404829614cb25ce2bf6ab/node_modules/meanio/node_modules/express-jwt/node_modules/jsonwebtoken/node_modules/jws/node_modules/base64url/node_modules/concat-stream/node_modules/inherits' -> '/tmp/build_462c2f46476404829614cb25ce2bf6ab/node_modules/inherits'
remote:        npm ERR! enoent This is most likely not a problem with npm itself
remote:        npm ERR! enoent and is related to npm not being able to find a file.
remote:        npm ERR! enoent

```

**Comment by rjVapes** [comment]
@timelf123 Any update on this?

**Comment by timelf123** [comment]
Seems to be an npm install issue. I tried again today and got a different result - the app never binds to a port:

```
➜  ✗ heroku logs -t
2015-12-15T18:27:34.774108+00:00 heroku[web.1]: Starting process with command `./node_modules/.bin/forever -m 5 server.js`
2015-12-15T18:27:37.030770+00:00 app[web.1]: warn:    --minUptime not set. Defaulting to: 1000ms
2015-12-15T18:27:37.032843+00:00 app[web.1]: warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
2015-12-15T18:27:38.253035+00:00 app[web.1]: forking  1
2015-12-15T18:27:38.262683+00:00 app[web.1]: forking  3
2015-12-15T18:27:38.241448+00:00 app[web.1]: for real!
2015-12-15T18:27:38.296543+00:00 app[web.1]: forking  5
2015-12-15T18:27:38.315022+00:00 app[web.1]: forking  7
2015-12-15T18:27:38.312786+00:00 app[web.1]: forking  6
2015-12-15T18:27:38.242588+00:00 app[web.1]: forking  0
2015-12-15T18:27:38.259915+00:00 app[web.1]: forking  2
2015-12-15T18:27:38.279253+00:00 app[web.1]: forking  4
2015-12-15T18:28:35.453274+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-12-15T18:28:35.453274+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-12-15T18:28:36.375586+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by timelf123** [comment]
After some more digging, I thought it might be a memory issue (was trying to use free Hobby dyno). Every once in a while I'd see something like this:
```
2015-12-29T16:40:47.888083+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-29T16:40:52.737644+00:00 heroku[web.1]: Starting process with command `./node_modules/.bin/forever -m 5 server.js`
2015-12-29T16:40:54.642074+00:00 app[web.1]: warn:    --minUptime not set. Defaulting to: 1000ms
2015-12-29T16:40:54.643485+00:00 app[web.1]: warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
2015-12-29T16:40:55.717712+00:00 app[web.1]: for real!
2015-12-29T16:40:55.724935+00:00 app[web.1]: forking  1
2015-12-29T16:40:55.730623+00:00 app[web.1]: forking  3
2015-12-29T16:40:55.743314+00:00 app[web.1]: forking  5
2015-12-29T16:40:55.755798+00:00 app[web.1]: forking  7
2015-12-29T16:40:55.718814+00:00 app[web.1]: forking  0
2015-12-29T16:40:55.728802+00:00 app[web.1]: forking  2
2015-12-29T16:40:55.732769+00:00 app[web.1]: forking  4
2015-12-29T16:40:55.748501+00:00 app[web.1]: forking  6
2015-12-29T16:41:06.348847+00:00 heroku[web.1]: Process running mem=563M(110.1%)
2015-12-29T16:41:06.348847+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2015-12-29T16:41:27.663582+00:00 heroku[web.1]: Process running mem=563M(110.1%)
2015-12-29T16:41:27.663582+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2015-12-29T16:41:48.709692+00:00 heroku[web.1]: Process running mem=563M(110.1%)
2015-12-29T16:41:48.709692+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2015-12-29T16:41:53.228862+00:00 app[web.1]: Error waiting for process to terminate: No child processes
2015-12-29T16:41:53.200751+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-12-29T16:41:53.200751+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-12-29T16:41:53.836078+00:00 heroku[web.1]: State changed from starting to crashed
```

After scaling my dyno up to standard with 1GB memory, the app still is unable to bind to a port and fails.

**Comment by joshsilverman** [comment]
I tried this `$ heroku config:set NODE_MODULES_CACHE=false` based on another ticket.

It solved this error for me: `npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/build_462c2f46476404829614cb25ce2bf6ab/node_modules/meanio/node_modules/express-jwt/node_modules/jsonwebtoken/node_modules/jws/node_modules/base64url/node_modules/concat-stream/node_modules/inherits' -> '/tmp/build_462c2f46476404829614cb25ce2bf6ab/node_modules/inherits'`

**Comment by timelf123** [comment]
Thanks, that fixes the `ENOENT` stuff but I am still missing `ms` and now get this:
`EPEERINVALID mongodb-core@1.2.26 requires a peer of kerberos@~0.0 but none was installed.`

**Comment by joshsilverman** [comment]
Try the following steps:

1) add ms and kerberos to your package.json: `npm install -S ms kerberos`
2) freeze all versions in your package.json: `npm update --save`
3) make sure node modules aren't being cached: `heroku config:set NODE_MODULES_CACHE=false`
4) redeploy

Also, could you cross post your question to stackoverflow? I can do a more detailed write-up there. I had trouble finding these steps, so it would be good to get them on stackoverflow.

**Comment by timelf123** [comment]
It's a dependency nightmare out here!

Thanks for the steps - now choking on `connect-modrewrite`. I installed and saved to package.json. After re-deploying I now get uglify errors on `mean.userprofiles`

```
016-01-14T18:04:48.567313+00:00 app[web.1]: Error in (function(){'use strict';
2016-01-14T18:04:48.567314+00:00 app[web.1]: 
2016-01-14T18:04:48.567315+00:00 app[web.1]: angular.module('mean.userprofiles').factory('UserProfiles', ['$resource',
2016-01-14T18:04:48.567316+00:00 app[web.1]:   function($resource) {
2016-01-14T18:04:48.567317+00:00 app[web.1]:     return $resource('api/userprofiles/:userId', {
2016-01-14T18:04:48.567317+00:00 app[web.1]:       userId: '@_id'
2016-01-14T18:04:48.567318+00:00 app[web.1]:     }, {
2016-01-14T18:04:48.567318+00:00 app[web.1]:       update: {
2016-01-14T18:04:48.567319+00:00 app[web.1]:         method: 'PUT',
2016-01-14T18:04:48.567320+00:00 app[web.1]:         userProfileId: '@_id'
2016-01-14T18:04:48.567320+00:00 app[web.1]:       }
2016-01-14T18:04:48.567321+00:00 app[web.1]:     });
2016-01-14T18:04:48.567321+00:00 app[web.1]:   }
2016-01-14T18:04:48.567322+00:00 app[web.1]: ]);
2016-01-14T18:04:48.567322+00:00 app[web.1]: 
2016-01-14T18:04:48.567323+00:00 app[web.1]: 
2016-01-14T18:04:48.567323+00:00 app[web.1]: // 'use strict';
2016-01-14T18:04:48.567324+00:00 app[web.1]: // angular.module('mean.userprofiles').factory('UserProfiles', ['$http',
2016-01-14T18:04:48.567325+00:00 app[web.1]: // 	function($http) {
2016-01-14T18:04:48.567325+00:00 app[web.1]: // 		return {
2016-01-14T18:04:48.567326+00:00 app[web.1]: // 			get: function(user) {
2016-01-14T18:04:48.567326+00:00 app[web.1]: // 				return $http({
2016-01-14T18:04:48.567327+00:00 app[web.1]: // 							url: '/api/userprofiles/' + user.userId,
2016-01-14T18:04:48.567328+00:00 app[web.1]: // 							method: 'get'
2016-01-14T18:04:48.567328+00:00 app[web.1]: // 						}).then(function(result) {
2016-01-14T18:04:48.567329+00:00 app[web.1]: // 							// console.log(result);
2016-01-14T18:04:48.567330+00:00 app[web.1]: // 							return result.data;
2016-01-14T18:04:48.567330+00:00 app[web.1]: // 						});
2016-01-14T18:04:48.567331+00:00 app[web.1]: // 			},
2016-01-14T18:04:48.567331+00:00 app[web.1]: // 			update: function(params) {
2016-01-14T18:04:48.567332+00:00 app[web.1]: // 					return $http({
2016-01-14T18:04:48.567332+00:00 app[web.1]: // 						'url': '/api/userprofiles/update/' + params._id,
2016-01-14T18:04:48.567333+00:00 app[web.1]: // 		        		'data': params,
2016-01-14T18:04:48.567334+00:00 app[web.1]: // 						'method': 'put'
2016-01-14T18:04:48.567334+00:00 app[web.1]: // 					})
2016-01-14T18:04:48.567335+00:00 app[web.1]: // 		      		.then(function(result) {
2016-01-14T18:04:48.567335+00:00 app[web.1]: // 						return result.data;
2016-01-14T18:04:48.567336+00:00 app[web.1]: // 					}, function(result) {
2016-01-14T18:04:48.567336+00:00 app[web.1]: // 						return result.data;
2016-01-14T18:04:48.567337+00:00 app[web.1]: // 					});
2016-01-14T18:04:48.567337+00:00 app[web.1]: 				
2016-01-14T18:04:48.567338+00:00 app[web.1]: // 			},
2016-01-14T18:04:48.567339+00:00 app[web.1]: // 			save: function(name, data) {
2016-01-14T18:04:48.567339+00:00 app[web.1]: 				
2016-01-14T18:04:48.567340+00:00 app[web.1]: // 			}
2016-01-14T18:04:48.567340+00:00 app[web.1]: // 		};
2016-01-14T18:04:48.567341+00:00 app[web.1]: // 	}
2016-01-14T18:04:48.567342+00:00 app[web.1]: // ]);})(); on line 48
2016-01-14T18:04:48.573917+00:00 app[web.1]: Unexpected token: eof (undefined)
2016-01-14T18:04:48.574168+00:00 app[web.1]: 
2016-01-14T18:04:48.574171+00:00 app[web.1]: /app/node_modules/meanio/lib/core_modules/module/aggregation.js:121
2016-01-14T18:04:48.574171+00:00 app[web.1]:     throw e;
2016-01-14T18:04:48.574172+00:00 app[web.1]:     ^
2016-01-14T18:04:48.574173+00:00 app[web.1]: Error
2016-01-14T18:04:48.574173+00:00 app[web.1]:     at new JS_Parse_Error (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:196:18)
2016-01-14T18:04:48.574174+00:00 app[web.1]:     at js_error (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:204:11)
2016-01-14T18:04:48.574175+00:00 app[web.1]:     at croak (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:680:9)
2016-01-14T18:04:48.574175+00:00 app[web.1]:     at token_error (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:688:9)
2016-01-14T18:04:48.574176+00:00 app[web.1]:     at unexpected (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:694:9)
2016-01-14T18:04:48.574177+00:00 app[web.1]:     at block_ (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:1006:28)
2016-01-14T18:04:48.574177+00:00 app[web.1]:     at /app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:980:25
2016-01-14T18:04:48.574178+00:00 app[web.1]:     at function_ (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:985:15)
2016-01-14T18:04:48.574178+00:00 app[web.1]:     at expr_atom (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:1193:24)
2016-01-14T18:04:48.574179+00:00 app[web.1]:     at maybe_unary (/app/node_modules/meanio/node_modules/uglify-js/lib/parse.js:1363:19)
2016-01-14T18:04:48.664630+00:00 app[web.1]: Worker 193 died :(

```

**Comment by math4ml** [comment]
:) I know what you mean -- no pun intended! Unfortunately, I haven't run into that problem, so I'm not sure how helpful I can be. I can point you here though: https://github.com/terinjokes/gulp-uglify/issues/50#issuecomment-60579843

That comment suggests adding a utility that will enable more informative errors.

**Comment by rjVapes** [comment]
The close of your IFFE is commented out Tim

**Comment by joshsilverman** [comment]
:) I know what you mean -- no pun intended! Unfortunately, I haven't run into that problem, so I'm not sure how helpful I can be. I can point you here though: https://github.com/terinjokes/gulp-uglify/issues/50#issuecomment-60579843

That comment suggests adding a utility that will enable more informative errors.

**Comment by timelf123** [comment]
@rjVapes my man! good catch. This is an unmodified core file, any idea why this is happening?

**Comment by rjVapes** [comment]
No idea, I've never seen UserProfiles before I assumed it was something you created.  Where is it from?

**Comment by timelf123** [comment]
Oops my bad we created this one:

```
'use strict';

angular.module('mean.userprofiles').factory('UserProfiles', ['$resource',
  function($resource) {
    return $resource('api/userprofiles/:userId', {
      userId: '@_id'
    }, {
      update: {
        method: 'PUT',
        userProfileId: '@_id'
      }
    });
  }
]);
```

**Comment by joshsilverman** [comment]
Change cpuCount in server.js to be a lower number (eg. 2) or have it set based on an environment variable.

**Comment by timelf123** [comment]
This community rocks. Removing the commented block from my `UserProfiles` solved the uglify issue


`var cpuCount = process.env.CPU_COUNT || require('os').cpus().length;` solved the CPU issue, PR incoming

Next up, more dep issues! I was missing a bunch of bower packages for /custom.  And because of that the aggregate.js file did not contain everything it needs. I tried to run this a few times, but many custom packages were still missing bower files. 
`heroku run npm run postinstall`

Typically I'd solve this with `mean postinstall` but the mean-cli is not available globally on heroku. To get around this I could add mean-cli to package.json deps and run like `heroku run ./node_modules/mean-cli/bin/mean-postinstall` but that seems unnecessarily complicated


Also, bower is being annoying and asking this every time (not persisting my answer)
`? May bower anonymously report usage statistics to improve the tool over time`

Fix is add `--config.interactive=false` to bower cmds. PR incoming as well

**Comment by rjVapes** [comment]
If a custom package has bower dependencies you can add this to your package.json for that package.
```
   "scripts": {
    "postinstall" : "bower install"
  },
```

**Comment by joshsilverman** [comment]
Another option:

`  "scripts": {
    "start": "node server",
    "mocha": "node tools/test/run-mocha.js",
    "karma": "node node_modules/karma/bin/karma start karma.conf.js",
    "test": "gulp test",
    "test-e2e": "gulp e2e.test",
    "postinstall": "node tools/scripts/postinstall.js"
  }, `

postinstall.js will run the following automatically:

`shell.exec('bower update', function(code) {
  console.log('    Updating Bower dependencies');
});`

**Comment by timelf123** [comment]
Thanks @rjVapes and @joshsilverman! Totally forgot about the postinstall trick. That should wrap up the bower issues.

Now onto the fixes for upstream
- CPU count can be set by env var
- Bower should be run in non-interactive mode

What about the missing ms/kerberos?

**Comment by rjVapes** [comment]
kerberos should be added to package.json and  then the shrinkwrap would need to be updated.  This is an npm3 issue as auto-installing peer dependencies has been deprecated, but should be fine to toss it there.  Not sure what the 'ms' issue is, other than seeing that it is in an issue in some cases.  Is it an optional dependencies that seems to be necessary on heroku or something?

**Comment by timelf123** [comment]
`ms` seems to be required by mongoose. I'll throw a few PRs together shortly

Down the rabbit hole we go...

I assume this is something malformed on my end, any clues on how to debug `Error loading modules [SyntaxError: Unexpected token }]`? No JSHint errors that I can see affecting this. 

```
2016-01-14T19:19:57.706402+00:00 app[web.1]: Error loading modules [SyntaxError: Unexpected token }]
2016-01-14T19:19:57.707432+00:00 app[web.1]: Mean app started on port 15827 (production) cluster.worker.id: 2
2016-01-14T19:19:58.602798+00:00 app[web.1]: Error loading modules [SyntaxError: Unexpected token }]
2016-01-14T19:19:58.604205+00:00 app[web.1]: Mean app started on port 15827 (production) cluster.worker.id: 1
2016-01-14T19:21:52.228675+00:00 heroku[router]: at=info method=GET path="/" host=iam-prediction-market.herokuapp.com request_id=f0aa1b51-5505-4711-abba-3966e9231840 fwd="184.58.195.125" dyno=web.1 connect=0ms service=37ms status=404 bytes=231
2016-01-14T19:21:52.219597+00:00 app[web.1]: Error: Failed to lookup view "404" in views directory "/app/views"

```

**Comment by rjVapes** [comment]
https://github.com/linnovate/meanio/blob/master/lib/core_modules/module/index.js#L113 returned with an error it seems.  Something along the way got rejected.  Do you have any packages without a package.json or the package.json lacks a 'mean' key value pair or something perhaps?

**Comment by timelf123** [comment]
Doh! Just a standard PEBCAK error. It turned out to be an extra comma in a custom `package.json` left behind in my hastiness. Re bower: Forgot we had fixed the bower postinstall stuff in https://github.com/linnovate/mean-cli/pull/124 - these are older custom packages that do not have a postinstall script.

@joshsilverman imho this is on topic as it affects the core mean experience. So far we have identified a few enhancements to the core meanio - configurable CPU counts, turning off bower nags, etc. That said I crossposted a quick post on SO http://stackoverflow.com/questions/34799310/mean-io-0-5-5-heroku-deploy-issues

**Comment by joshsilverman** [comment]
@timelf123 I was thinking they were more configuration/settings changes as opposed to Mean issues. However, I think you're right that they belong here too. Presumably, the Heroku deploy process should be much easier with Mean (similar to Rails which is very straightforward to get going on Heroku). Regardless, I'm glad they are better documented now.

**Comment by timelf123** [comment]
:+1: thank you for your guidance @joshsilverman @rjVapes

**Comment by rjVapes** [comment]
np, if you can get to a point where it's easy to deploy a default mean app to heroku, and document the steps, you'll make a lot of people happy I think :)
