### ISSUE TITLE
Mean.Io Error

### ISSUE THREAD

**Issue by jahanzaib-kk** [linnovate/mean#1434]
I am facing an issue while running the mean.io application can some one look at this what is the problem.
  at F:\Client_Rafat_New_Repo\fnb-frontend\webui\node_modules\meanio\lib\core_modules\module\util.js:23:7
    at Array.forEach (native)
    at Object.walk (F:\Client_Rafat_New_Repo\fnb-frontend\webui\node_modules\meanio\lib\core_modules\module\util.js:16:25)
    at customerKlass.Module.routes (F:\Client_Rafat_New_Repo\fnb-frontend\webui\node_modules\meanio\lib\core_modules\module\index.js:175:10)
    at F:\Client_Rafat_New_Repo\fnb-frontend\webui\packages\custom\customers\app.js:51:19
    at Dependency.Dependable.runAction (F:\Client_Rafat_New_Repo\fnb-frontend\webui\node_modules\meanio\node_modules\lazy-dependable\index.js:73:22)

**Comment by claustres** [comment]
Please provide more information (MEAN.io version, code snippets, etc.) because it seems to be related to your code in the cutom 'customers' package (cf. **F:\Client_Rafat_New_Repo\fnb-frontend\webui\packages\custom\customers\app.js:51:19**).
