### ISSUE TITLE
Problem when start

### ISSUE THREAD

**Issue by tuanflour** [linnovate/mean#1525]
when I start by: $ node server
it throw error like that:

[16:11:21] Finished 'webpack:build-dev' after 28 s
[16:11:21] Starting 'development'...
[16:11:21] Finished 'development' after 41 μs
[16:11:21] [nodemon] restarting due to changes...
[16:11:21] [nodemon] app crashed - waiting for file changes before starting...

util.js:555
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:555:27)
    at Object.<anonymous> (/home/user/giasu/node_modules/meanio/lib/core_modules/events/events.js:10:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/user/giasu/node_modules/meanio/lib/core_modules/module/index.js:11:14)

and can not load page: http://localhost:3000/

**Comment by mccullya** [comment]
FYI @tuanflour I fixed this personally by changing the version of Node I was using (changed to latest)

**Comment by tuanflour** [comment]
Thank for you support, I will try on your way!
