### ISSUE TITLE
Error when accessing application

### ISSUE THREAD

**Issue by glefevre** [linnovate/mean#1538]
I just created a new mean app using the mean-cli and following the instructions here (http://learn.mean.io/#mean-stack-installation-install-the-mean-cli). When I start the server, I don't have any errors but when I tried to access http://localhost:3000, I ran into this error : 
node_modules/meanio-circles/server/models/circle.js:30
    circles.forEach(function(circle) {
           ^

TypeError: Cannot read property 'forEach' of undefined
    at /home/gildas/Dev/MEAN/NuxeoAppli/node_modules/meanio-circles/server/models/circle.js:30:12
    at /home/gildas/Dev/MEAN/NuxeoAppli/node_modules/mongoose/lib/query.js:2171:21
    at /home/gildas/Dev/MEAN/NuxeoAppli/node_modules/kareem/index.js:160:11
    at Immediate.cb (/home/gildas/Dev/MEAN/NuxeoAppli/node_modules/mongoose/lib/query.js:1031:14)
    at Immediate._onImmediate (/home/gildas/Dev/MEAN/NuxeoAppli/node_modules/mquery/lib/utils.js:137:16)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback](timers.js:514:5)
Worker 7 died :(

Does anyone have an idea where it could come from?
Thank you for your help!
Gildas

**Comment by smallporgies** [comment]
I have the same problem exactly after creating a clean project.
 - OS X 10.11.4 (15E65)
 - npm 3.8.6
 - node v6.0.0

**Comment by smallporgies** [comment]
Ok so the reason is that there is an error coming back from mongo when circles are loaded - 
```javascript
{ MongoError: not authorized on mean-dev to execute command { find: "circles", filter: {}, sort: { circle: 1 } } 
    at Function.MongoError.create (/<my-project-path>/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/<my-project-path>/node_modules/mongodb-core/lib/cursor.js:200:36)
    at Callbacks.emit (/<my-project-path>/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/<my-project-path>/node_modules/mongodb-core/lib/topologies/server.js:358:23)
    at Socket.<anonymous> (/<my-project-path>/node_modules/mongodb-core/lib/connection/connection.js:292:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:535:20)
  name: 'MongoError',
  message: 'not authorized on mean-dev to execute command { find: "circles", filter: {}, sort: { circle: 1 } }',
  ok: 0,
  errmsg: 'not authorized on mean-dev to execute command { find: "circles", filter: {}, sort: { circle: 1 } }',
  code: 13 }
```

It would be great if a helpful error message could be logged instead of ignoring the error!

**Comment by smallporgies** [comment]
For what it's worth, in my case the cause was running two conflicting mongo instances somehow (don't know how they both were happy with the port situation), one of which had security settings set up. This came from the bitnami mean local install which I'd forgotten I'd left running from earlier experimentation, so it may be worth checking you don't have something like that running!

**Comment by liorkesos** [comment]
I was not able to replicate. Can you try to add the missing error warning
in a suitable format and submit a PR?

**Comment by returnonclick** [comment]
Same error, I've tried to update the meanio-circles but didnt work

**Comment by CharlesHamel** [comment]
Me too same problem using the bitnami image in production on AWS
