### ISSUE TITLE
TypeError: auth.findUser is not a function

### ISSUE THREAD

**Issue by noyg** [linnovate/mean#1561]
Upgraded to latest 0.9.1 and 0.6.1.
For every request, I get:
`TypeError: auth.findUser is not a function
    at c:\projects\marq\node_modules\meanio-users\server\routes\users.js:25:12
    at Layer.handle [as handle_request] (c:\projects\marq\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\projects\marq\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (c:\projects\marq\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\projects\marq\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\layer.js:95:5)
    at c:\projects\marq\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (c:\projects\marq\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\index.js:330:12)
    at next (c:\projects\marq\node_modules\meanio\lib\core_modules\server\node_modules\express\lib\router\index.js:271:10)
    at Query.<anonymous> (c:\projects\marq\node_modules\meanio-users\server\controllers\users.js:217:24)
    at c:\projects\marq\node_modules\kareem\index.js:177:19
    at c:\projects\marq\node_modules\kareem\index.js:109:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)`

Function really does not exist in core authorization.js

**Comment by pashist** [comment]
`auth` was removed since 0.6 :(
if you still need to use it try follow: copy authorisation.js from prev version of mean to your package and register it in `packages/custom/your-package/app.js` **before** your module registration like this: 
```
require('meanio').register('auth', require('./authorization'));

YourModule.register(function(app, auth ...
```
hope this help

**Comment by noyg** [comment]
I know. That's the reason I attached the traces. It's being called at `meanio-users\server\controllers\users.js:217:24`, which is core code. Not my code.

**Comment by noyg** [comment]
Also, @pashist , that's only half true since `auth` does exist in core 0.6.1 with `auth.isMongoId'

**Comment by pashist** [comment]
You right, @noyg, i just mean was removed all authentication features from it.
Also i made PR to meanio-users package which should fix `api/loggedin` route, only we need some time to merge it.

**Comment by noyg** [comment]
@pashist Great! any ETA on that?

**Comment by liorkesos** [comment]
Reviewing @pashist PR - https://github.com/linnovate/meanio-users/pull/2

**Comment by igorg1312** [comment]
Hi i send a bug perm denied in configstore/bower-github.json

Reviewing @pashist <https://github.com/pashist> PR -
linnovate/meanio-users#2 <https://github.com/linnovate/meanio-users/pull/2>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/linnovate/mean/issues/1561#issuecomment-217727783>

**Comment by igorg1312** [comment]
Also a unsafe perm From access denied, remove automatic script on exit
tild/.*-rc.json
Il 08 Mag 2016 19:17, "Igor" <igorgarofano@gmail.com> ha scritto:
