### ISSUE TITLE
mean init myMeanApp failed - OSX

### ISSUE THREAD

**Issue by Shane24** [linnovate/mean#1563]
`sudo mean init App
Password:
module.js:339
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mean-cli/lib/controllers/anonymized-data.js:8:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)`

Running:

OSX 10.11
Node v4.2.3
MongoDB shell version: 3.2.6

**Comment by igorg1312** [comment]
Ok: sudo clown -R  $USER: $GROUP ~/.npm do the same with .conf directory,
and reinstall module
Il 09 Mag 2016 11:41, "Shane24" <notifications@github.com> ha scritto:

**Comment by Shane24** [comment]
All of ~/.npm is drwxr-xr-x

Reinstall module? Could you explain a bit further? Thanks

**Comment by Shane24** [comment]
I ask to explain further as it's my understanding that module.js is a dev/project dependency, not a global one? So I'm not sure how to reinstall it since init is failing?

**Comment by Shane24** [comment]
FIXED.

Installing 'request' globally has fixed the issue.

'request' should probably be a dev dependency though, rather than global?

Anyway, thanks for the help.

**Comment by bransbury** [comment]
This is an issue with mean-cli - I've added a PR to fix this here:
https://github.com/linnovate/mean-cli/pull/133
