### ISSUE TITLE
Error throws on creating admin user

### ISSUE THREAD

**Issue by AttilaSATAN** [linnovate/mean#1580]
Hi everyone!
I'm using windows 10. 
when `mean-cli` asks for admin user's email in prompt window the app crashes. If you skip that option CLI clones the repo successfully.

here is the stack trace of the crash.

`at thrower (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:77:15)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5894:30)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at TakeObserver.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:5
652:59)
    at TakeObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\n
ode_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at TakeObserver.tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx
.js:63:31)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5892:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at InnerObserver.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:
5764:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\
node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
Trace
    at thrower (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:77:15)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5894:30)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at InnerObserver.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:
5764:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\
node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at InnerObserver.tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\r
x.js:63:31)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5892:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at Subject.Rx.Subject.addProperties.onError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_m
odules\rx\dist\rx.js:5985:19)
    at Subject.tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:6
3:31)
Trace
    at thrower (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:77:15)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5894:30)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at Subject.Rx.Subject.addProperties.onError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_m
odules\rx\dist\rx.js:5985:19)
    at Subject.tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:6
3:31)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5892:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at AutoDetachObserver.tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\d
ist\rx.js:63:31)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5892:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
Trace
    at thrower (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:77:15)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5894:30)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at AutoDetachObserver.tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\d
ist\rx.js:63:31)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5892:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at InnerObserver.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:
3767:21)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\
node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at InnerObserver.tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\r
x.js:63:31)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5892:52)
Trace
    at thrower (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:77:15)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5894:30)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at InnerObserver.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:
3767:21)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\
node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at InnerObserver.tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\r
x.js:63:31)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5892:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at scheduleError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:2420:9
)
    at schedule (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1313:53)
Trace
    at thrower (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:77:15)
    at AutoDetachObserverPrototype.error (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\
rx\dist\rx.js:5894:30)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Attila\AppData\Roaming\nvm\v5
.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1773:14)
    at scheduleError (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:2420:9
)
    at schedule (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1313:53)
    at tryCatcher (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:63:31)
    at runTask (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1197:38)
    at Immediate._onImmediate (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.
js:1231:36)
    at processImmediate [as _immediateCallback] (timers.js:516:17)
Trace
    at thrower (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:77:15)
    at runTask (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.js:1200:38)
    at Immediate._onImmediate (C:\Users\Attila\AppData\Roaming\nvm\v5.9.0\node_modules\mean-cli\node_modules\rx\dist\rx.
js:1231:36)
    at processImmediate [as _immediateCallback] (timers.js:516:17)`

**Comment by NateRedding** [comment]
I am getting the same error it would seem. I'm using Mac OS X 10.11.5, with Node 5.9.1:

```
/Users/nateredding/.nvm/versions/node/v5.9.1/lib/node_modules/mean-cli/node_modules/rx/dist/rx.js:77
    throw e;
    ^
true
```

**Comment by giano** [comment]
Same here

**Comment by randal-io** [comment]
Also getting this error. I'm on Ubuntu 14.04 and i copy/pasted your install instructions on a fresh server.

/usr/lib/node_modules/mean-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:77
    throw e;
    ^
true

**Comment by sravan464** [comment]
# i got this error on windows 10 , mongo DB : 3.2.9 
 **Error Connecting to database: { [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017' }**

**Comment by timelf123** [comment]
this should be posted in linnovate/mean-cli
