### ISSUE TITLE
Cannot read property 'decendants' of undefined meanio-circles

### ISSUE THREAD

**Issue by timelf123** [linnovate/mean#1613]
```
TypeError: Cannot read property 'decendants' of undefined
    at /app/node_modules/meanio-circles/server/models/circle.js:58:68
   at Array.forEach (native)
    at /app/node_modules/meanio-circles/server/models/circle.js:55:20
   at Array.forEach (native)
    at /app/node_modules/meanio-circles/server/models/circle.js:49:15
```

This error showed up in these builds:
https://travis-ci.org/linnovate/mean/jobs/102957001
https://travis-ci.org/linnovate/mean/jobs/102961750

It has now resurfaced randomly for everyone in my team.

**Comment by timelf123** [comment]
Turns out it was a bad db entry
