### ISSUE TITLE
Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by mengkeys** [linnovate/mean#1623]
Invoking gulp - development
[09:43:25] Using gulpfile ~/Project/mean/my-blog/gulpfile.js
[09:43:25] Starting 'clean'...
[09:43:25] Finished 'clean' after 4.83 ms
[09:43:25] Starting 'default'...
[09:43:25] Starting 'webpack:build-dev'...
[09:43:25] Starting 'clean'...
[09:43:25] Starting 'less'...
[09:43:25] Starting 'sass'...
[09:43:25] Starting 'csslint'...
[09:43:25] Starting 'env:development'...
[09:43:25] Finished 'env:development' after 16 μs
[09:43:25] Starting 'devServe'...
[09:43:26] Finished 'devServe' after 73 ms
[09:43:26] Starting 'watch'...
[09:43:26] Finished 'watch' after 390 ms
[09:43:26] Finished 'clean' after 901 ms
[09:43:26] [nodemon] 1.10.0
[09:43:26] [nodemon] to restart at any time, enter `rs`
[09:43:26] [nodemon] watching: *.*
[09:43:26] [nodemon] starting `node --debug server.js`
Debugger listening on port 5858
[09:43:26] Finished 'less' after 1.24 s
[09:43:26] Finished 'sass' after 985 ms
[09:43:26] [webpack:build-dev] Hash: a8197b403f77f10f8a0d
Version: webpack 1.13.1
Time: 1297ms

ERROR in ./app.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/xtech"
    at /home/xtech/Project/mean/my-blog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:313:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/xtech/Project/mean/my-blog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/home/xtech/Project/mean/my-blog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/home/xtech/Project/mean/my-blog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (/home/xtech/Project/mean/my-blog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/home/xtech/Project/mean/my-blog/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/home/xtech/Project/mean/my-blog/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/home/xtech/Project/mean/my-blog/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/xtech/Project/mean/my-blog/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/home/xtech/Project/mean/my-blog/node_modules/babel-loader/index.js:88:12)
[09:43:26] Finished 'webpack:build-dev' after 1.3 s
[09:43:26] csslint: 3 files lint free
[09:43:26] Finished 'csslint' after 1.08 s
[09:43:26] Starting 'development'...
[09:43:26] Finished 'development' after 3.22 μs
Mean app started on port 3000 (development) cluster.worker.id: 0
[09:43:28] index.html reloaded.
GET / - - - - ms
GET / - - - - ms

**Comment by timelf123** [comment]
`npm install` again
