### ISSUE TITLE
Certificate expiry error in mean.io

### ISSUE THREAD

**Issue by vijaygurajala** [linnovate/mean#1630]
When I installed all the tools required and started working on the Mean stack from mean.io documentation page. I tried to create users in mean and when I given a password, I go below error. What can I do here?

{ Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'CERT_HAS_EXPIRED' }

**Comment by VikramTiwari** [comment]
Related to this https://github.com/linnovate/meanio/issues/117 Closing here.
