### ISSUE TITLE
npm ERR! Failed at the mean@0.7.0 snyk-protect script 'snyk protect'

### ISSUE THREAD

**Issue by ruslanss** [linnovate/mean#1684]
Win10 64x, node  v6.8.0, npm v3.10.8
npm install

```
PS C:\git\myApp> npm install

> mean@0.7.0 postinstall C:\git\myApp
> node tools/scripts/postinstall.js

Auto installing package dependencies
bower web-bootstrap#*             copy C:\git\myApp\node_modules\meanio\resources\web-bootstrap.js
bower angular#*                 cached https://github.com/angular/bower-angular.git#1.5.8
bower angular#*               validate 1.5.8 against https://github.com/angular/bower-angular.git#*
bower angular-resource#*        cached https://github.com/angular/bower-angular-resource.git#1.5.8
bower angular-resource#*      validate 1.5.8 against https://github.com/angular/bower-angular-resource.git#*
bower jquery#*                  cached https://github.com/jquery/jquery-dist.git#3.1.1
bower jquery#*                validate 3.1.1 against https://github.com/jquery/jquery-dist.git#*
bower angular-cookies#*         cached https://github.com/angular/bower-angular-cookies.git#1.5.8
bower angular-cookies#*       validate 1.5.8 against https://github.com/angular/bower-angular-cookies.git#*
bower angular-mocks#*           cached https://github.com/angular/bower-angular-mocks.git#1.5.8
bower angular-mocks#*         validate 1.5.8 against https://github.com/angular/bower-angular-mocks.git#*
bower angular-route#*           cached https://github.com/angular/bower-angular-route.git#1.5.8
bower angular-route#*         validate 1.5.8 against https://github.com/angular/bower-angular-route.git#*
bower bootstrap#*               cached https://github.com/twbs/bootstrap.git#3.3.7
bower bootstrap#*             validate 3.3.7 against https://github.com/twbs/bootstrap.git#*
bower angular-bootstrap#*       cached https://github.com/angular-ui/bootstrap-bower.git#2.2.0
bower angular-bootstrap#*     validate 2.2.0 against https://github.com/angular-ui/bootstrap-bower.git#*
bower angular-ui-router#*       cached https://github.com/angular-ui/angular-ui-router-bower.git#0.3.1
bower angular-ui-router#*     validate 0.3.1 against https://github.com/angular-ui/angular-ui-router-bower.git#*
bower angular-ui-select#*       cached https://github.com/angular-ui/ui-select.git#0.19.4
bower angular-ui-select#*     validate 0.19.4 against https://github.com/angular-ui/ui-select.git#*
bower angular-sanitize#*        cached https://github.com/angular/bower-angular-sanitize.git#1.5.8
bower angular-sanitize#*      validate 1.5.8 against https://github.com/angular/bower-angular-sanitize.git#*
bower web-bootstrap#*         resolved C:\git\myApp\node_modules\meanio\resources\web-bootstrap.js
    Updating Bower dependenciesadata: sill mapToRegistry uri https://registry.npmjs.org/ng-clip
mean@0.7.0 C:\git\myApp
+-- meanio-admin@0.1.7  (git://github.com/linnovate/meanio-admin.git#0e9d428c67789aadf5615f7d1a109716d3375ad4)
+-- meanio-circles@0.1.1  (git://github.com/linnovate/meanio-circles.git#3fd8e32af3374dcfc34026b7f86e9d332df2b3a6)
+-- meanio-system@0.1.3  (git://github.com/linnovate/meanio-system.git#a1b1b2b35eec858493d3a308e56d1e2014627ed5)
`-- meanio-users@0.1.4  (git://github.com/linnovate/meanio-users.git#b1084c608bbf17e879668e1392a664919151fa42)

    Dependencies installed for package meanStarter

> mean@0.7.0 prepublish C:\git\myApp
> npm run snyk-protect


> mean@0.7.0 snyk-protect C:\git\myApp
> snyk protect

Snyk couldn't patch the specified vulnerabilities because GNU's patch is not available. Please install 'patch' and try a
gain.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\git\\myApp\\node_modules\\npm\\bin\\npm-cli.js" "run" "snyk-pro
tect"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! mean@0.7.0 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean@0.7.0 snyk-protect script 'snyk protect'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     snyk protect
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\myApp\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\boss\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm
-cli.js" "install"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! mean@0.7.0 prepublish: `npm run snyk-protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean@0.7.0 prepublish script 'npm run snyk-protect'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run snyk-protect
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\myApp\npm-debug.log
```

**Comment by ruslanss** [comment]
```
PS C:\git\myApp> mean status

    MEAN Status
    -----------

    MEAN VERSION: 0.7.0

    Error Connecting to database: { Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017' }
PS C:\git\myApp>
```

**Comment by adrukh** [comment]
@ruslanss regarding `snyk protect` issue, please install `patch.exe` binary and expose it in your path per the instructions in https://github.com/Snyk/snyk/issues/45#issuecomment-250145966

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`

**Comment by albertxavier001** [comment]
Install snyk for global: `npm install snyk -g`
Delete `node_modules` folder
Install again: `npm install`
