### ISSUE TITLE
Error: failed to connect to [localhost:27017]

### ISSUE THREAD

**Issue by tomgersic** [linnovate/mean#175]
I'm trying to get a fresh install of mean.io working. I cloned the Repository from Github, and used "npm install" as the directions specify. When I try to start the server with "node server", I get this error:

Express app started on port 3000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/tomgersic/Development/dotty/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:540:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/Users/tomgersic/Development/dotty/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/Users/tomgersic/Development/dotty/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)

**Comment by Climax777** [comment]
`tail -f /var/log/mongodb/mongod.log`
