### ISSUE TITLE
error installing via dockerfile

### ISSUE THREAD

**Issue by AntonioFernandezFernandez** [linnovate/mean#1784]
when i install mean.io via dockerfile i get an error finding mongoose library:

`ror: Cannot find module 'mongoose'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/node_modules/meanio-users/server/models/user.js:6:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireModel (/usr/src/app/node_modules/meanio/lib/core_modules/module/index.js:116:19)
    at /usr/src/app/node_modules/meanio/lib/core_modules/module/util.js:21:7
    at Array.forEach (native)
    at walk (/usr/src/app/node_modules/meanio/lib/core_modules/module/util.js:16:25)
    at /usr/src/app/node_modules/meanio/lib/core_modules/module/util.js:23:7
    at Array.forEach (native)
    at Object.walk (/usr/src/app/node_modules/meanio/lib/core_modules/module/util.js:16:25)
    at MeanUserKlass.Module (/usr/src/app/node_modules/meanio/lib/core_modules/module/index.js:134:14)
    at new MeanUserKlass (/usr/src/app/node_modules/meanio-users/app.js:10:10)
    at Object.<anonymous> (/usr/src/app/node_modules/meanio-users/app.js:21:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Module.activate (/usr/src/app/node_modules/meanio/lib/core_modules/module/dependablelist.js:52:15)
Sat, 22 Apr 2017 18:31:13 GMT cluster Worker 319 died :(
/usr/src/app/node_modules/q/q.js:155
                throw e;
`

is there any error in dockerfile or maybe i'm doing something wrong?

**Comment by rogeriob2br** [comment]
Hi,  If I'm not mistaken try:
1) add in docker file : 
RUN npm install mongoose -g

2) add mongoose latest version in package.jason "dependencies": 
 like this: https://stackoverflow.com/a/38589495/6568661

**Comment by rogeriob2br** [comment]
Hi,  try change the git clone to "https://github.com/linnovate/mean/tree/1.x"
