### ISSUE TITLE
Error while running angular 4 express mongodb nodejs project

### ISSUE THREAD

**Issue by christianwenego** [linnovate/mean#1807]
E:\node\dwaapp>node app.js
Server started on port 3000
Connected to database mongodb @ 27017
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\node\dwaapp\node_modules\express\lib\response.js:730:10)
    at ServerResponse.json (E:\node\dwaapp\node_modules\express\lib\response.js:253:10)
    at E:\node\dwaapp\routes\employeRoute.js:10:13
    at Query.<anonymous> (E:\node\dwaapp\node_modules\mongoose\lib\model.js:3753:16)
    at E:\node\dwaapp\node_modules\kareem\index.js:277:21
    at E:\node\dwaapp\node_modules\kareem\index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by rogeriob2br** [comment]
Hi, see this [Stack answer](https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client#answer-7086621) for a similar question.
