### ISSUE TITLE
Cant download mean.io and run server?

### ISSUE THREAD

**Issue by MiloshN** [linnovate/mean#1840]
$ npm install
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-ZpYajIfO0j2cOFTO955KUMIKNmj6zhX8kVztMAxFsDaMwz+9Z9SV0uou2pC9HJqcfpffOsjnbrDMvkNy+9RXPw== integrity checksum failed when using sha512: wanted sha512-ZpYajIfO0j2cOFTO955KUMIKNmj6zhX8kVztMAxFsDaMwz+9Z9SV0uou2pC9HJqcfpffOsjnbrDMvkNy+9RXPw== but got sha1-RcZikJTeTpb2k+9+q3SuB5wkD8E=. (3480 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> node-sass@4.5.3 install C:\Users\milos\Desktop\testing-meanio\mean\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\milos\AppData\Roaming\npm-cache\node-sass\4.5.3\win32-x64-48_binding.node

> innograph@1.0.0 postinstall C:\Users\milos\Desktop\testing-meanio\mean\node_modules\innograph
> npm run build

npm WARN invalid config loglevel="notice"

> innograph@1.0.0 build C:\Users\milos\Desktop\testing-meanio\mean\node_modules\innograph
> babel src --out-dir dist

src\controllers\index.js -> dist\controllers\index.js
src\controllers\post.controller.js -> dist\controllers\post.controller.js
src\controllers\profile.controller.js -> dist\controllers\profile.controller.js
src\index.js -> dist\index.js
src\schema\index.js -> dist\schema\index.js
src\schema\mutations\index.js -> dist\schema\mutations\index.js
src\schema\mutations\post\add.js -> dist\schema\mutations\post\add.js
src\schema\mutations\post\index.js -> dist\schema\mutations\post\index.js
src\schema\mutations\post\remove.js -> dist\schema\mutations\post\remove.js
src\schema\mutations\post\update.js -> dist\schema\mutations\post\update.js
src\schema\queries\index.js -> dist\schema\queries\index.js
src\schema\queries\post\index.js -> dist\schema\queries\post\index.js
src\schema\queries\post\multiple.js -> dist\schema\queries\post\multiple.js
src\schema\queries\post\single.js -> dist\schema\queries\post\single.js
src\schema\queries\profile\index.js -> dist\schema\queries\profile\index.js
src\schema\queries\profile\single.js -> dist\schema\queries\profile\single.js
src\schema\types\post-input.js -> dist\schema\types\post-input.js
src\schema\types\post.js -> dist\schema\types\post.js
src\schema\types\profile.js -> dist\schema\types\profile.js

> node-sass@4.5.3 postinstall C:\Users\milos\Desktop\testing-meanio\mean\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\milos\Desktop\testing-meanio\mean\node_modules\node-sass\vendor\win32-x64-48\binding.node
Testing binary
Binary is fine

> Mean@2.0.1 postinstall C:\Users\milos\Desktop\testing-meanio\mean
> npm run webdriver:update

npm WARN invalid config loglevel="notice"

> Mean@2.0.1 webdriver:update C:\Users\milos\Desktop\testing-meanio\mean
> webdriver-manager update

[23:04:18] I/file_manager - creating folder C:\Users\milos\Desktop\testing-meanio\mean\node_modules\protractor\node_modules\webdriver-manager\selenium
[23:04:22] I/update - chromedriver: unzipping chromedriver_2.33.zip
[23:04:26] I/update - geckodriver: unzipping geckodriver-v0.19.0.zip
added 1363 packages in 797.145s

----------------

 $ npm start

 Mean@2.0.1 start C:\Users\milos\Desktop\testing-meanio\mean
 concurrently "npm run server:dev" "nodemon --watch server server-start.js"

 Error occured when executing command: nodemon --watch server server-start.js
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1020:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
     at onErrorNT (internal/child_process.js:376:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:389:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:502:3
 Error occured when executing command: nodemon --watch server server-start.js
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1020:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
     at onErrorNT (internal/child_process.js:376:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:389:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:502:3
[1] nodemon --watch server server-start.js exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Mean@2.0.1 start: `concurrently "npm run server:dev" "nodemon --watch server server-start.js" 
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Mean@2.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\milos\AppData\Roaming\npm-cache\_logs\2017-10-05T21_05_17_251Z-debug.log

**Comment by chanakaDe** [comment]
@MiloshN  Hey buddy,
What's the node version you are using  ? you must use node 6.x.
and also please take following steps.

First run this:
```
npm cache clear --force
```
Then you have to re install all:
```
npm install --no-shrinkwrap --update-binary
```
And make sure you have Python insalled in your system.
