### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by LukeN57** [linnovate/mean#1842]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Yes

* **What is the current behavior?**
after git clone, I am trying to npm install && npm start
npm install starts and then closes the node command line

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
install all dependencies and launch the application (probably on localhost:3000)

**Comment by chanakaDe** [comment]
@LukeN57  Hello buddy,
I checked your code. And I'm sorry i can't get a clear understanding about your error.
You are telling a issue when you running `npm install` , but you have provided some sample code block. Anyway, please provide us the error you are getting in the terminal when you are running the command ?  And what is the OS you are using ? what Node and NPM versions ?

**Comment by LukeN57** [comment]
Apologies for the lack of information. I'm running: 

- OS - Windows 10
- Node v6.11.3 
- npm version 3.10.10

I didn't provide a code block because nothing happens when executing the command _$npm install_ except that the node terminal (node command line) appears to start installing dependencies and then closes before it finishes. If I execute the command _$npm install && npm start_ the same thing happens. 

I've pasted below the code that I get after executing _$npm install_ and then reopening the node terminal window and executing _$npm start_. The errors don't surprise me because the install didn't seem to ever happen.

```
> Mean@2.0.1 start C:\Users\Luke\Documents\mean
> concurrently "npm run server:dev" "nodemon --watch server server-start.js"

'concurrently' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Mean@2.0.1 start: `concurrently "npm run server:dev" "nodemon --watch server server-start.js" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Mean@2.0.1 start script 'concurrently "npm run server:dev" "nodemon --watch server server-start.js" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run server:dev" "nodemon --watch server server-start.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Mean
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Luke\Documents\mean\npm-debug.log
```

**Comment by LukeN57** [comment]
I think I figured out the problem. I needed to install Python. This is not obvious from the mean.io homepage and I only figured it out by combing through past issues.

**Comment by frankwang0909** [comment]
Why you have to install Python?

**Comment by frankwang0909** [comment]
When I run `npm install`， I also failed to install the packages. Instead, I  got this info:
```shell
> Mean@2.0.1 postinstall G:\LEARN\MEAN\mean
> npm run webdriver:update


> Mean@2.0.1 webdriver:update G:\LEARN\MEAN\mean
> webdriver-manager update

[10:57:03] I/file_manager - creating folder G:\LEARN\MEAN\mean\node_modules\protractor\node_modules\
webdriver-manager\selenium
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TLSWrap.onread (net.js:563:26)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "run" "webdriver:update"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! Mean@2.0.1 webdriver:update: `webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Mean@2.0.1 webdriver:update script 'webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\LEARN\MEAN\mean\npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN angular2-universal@2.0.11 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none was installed.
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none was installed
.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none was instal
led.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none was inst
alled.
npm WARN apollo-link@0.8.0 requires a peer of graphql@^0.11.3 but none was installed.
npm WARN preload-webpack-plugin@1.2.3 requires a peer of webpack@^3.2.0 but none was installed.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! Mean@2.0.1 postinstall: `npm run webdriver:update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Mean@2.0.1 postinstall script 'npm run webdriver:update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run webdriver:update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\LEARN\MEAN\mean\npm-debug.log
```

**Comment by frankwang0909** [comment]
OS: Win 10

node v6.2.0

npm  v3.8.9

**Comment by chanakaDe** [comment]
If you are working on Windows , you must install python. It's mentioned in mean documentation in readme.md
