### ISSUE TITLE
Unable to connect to database: mongodb://localhost/new-mean

### ISSUE THREAD

**Issue by LukeN57** [linnovate/mean#1845]
I am imagining that this is a mongo problem, but not sure what to do to fix it. 

`C:\Users\Luke\Documents\mean>npm start

> Mean@2.0.1 start C:\Users\Luke\Documents\mean
> concurrently "npm run server:dev" "nodemon --watch server server-start.js"

[1] [nodemon] 1.12.1
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: C:\Users\Luke\Documents\mean\server/**/*
[1] [nodemon] starting `node server-start.js`
[0]
[0] > Mean@2.0.1 server:dev C:\Users\Luke\Documents\mean
[0] > npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/
[0]
[1] (node:128) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[1] server started on port 4040 (development)
[0]
[0] > Mean@2.0.1 webpack-dev-server C:\Users\Luke\Documents\mean
[0] > node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"
[0]
[1] C:\Users\Luke\Documents\mean\server.js:38
[1]   throw new Error('unable to connect to database: ' + mongoUri);
[1]   ^
[1]
[1] Error: unable to connect to database: mongodb://localhost/new-mean
[1]     at NativeConnection.<anonymous> (C:/Users/Luke/Documents/mean/server.js:22:9)
[1]     at emitOne (events.js:96:13)
[1]     at NativeConnection.emit (events.js:188:7)
[1]     at Immediate.<anonymous> (C:\Users\Luke\Documents\mean\node_modules\mongoose\lib\connection.js:325:19)
[1]     at runCallback (timers.js:672:20)
[1]     at tryOnImmediate (timers.js:645:5)
[1]     at processImmediate [as _immediateCallback] (timers.js:617:5)
[1] [nodemon] app crashed - waiting for file changes before starting...`

**Comment by matsum0623** [comment]
Have you started mongoDB?
`npm start` do not start mongoDB.

**Comment by chanakaDe** [comment]
Hello @LukeN57 ,
Please check this solution and tell if it's working. You have to use different MongoDB instance to check where is the issue, MongoDB itself or MEAN.
So go to https://mlab.com and create free account. Then you can create free MongoDB instance.
In the project root folder structure, you can find “server-start.js” file. All you have to do is change a one line like this.
```
process.env.MONGO_HOST='mongodb://<dbuser>:<dbpassword>@ds135574.mlab.com:35574/new-mean'
```

All you need to do is, create a database instance named “new-mean” in your free mLab account and then you can see connection link when you enter the instance in mLab account. Replace <user> and <password> with your details.

**Comment by chanakaDe** [comment]
@LukeN57 Did you find a solution ?
