### ISSUE TITLE
 proxy request /api/graphql  ECONNREFUSED

### ISSUE THREAD

**Issue by graffaello** [linnovate/mean#1852]
Hi all,
I'm submitting a  bug report
I'm very new to MEAN so I followed all the steps to install it on Windows 10 Pro as stated here http://mean.io/blog/
Everything seems to be installed fine, I run npm start and on the browser localhost:3000 is open properly.
When I click on the link "Posts" the page is switched properly but in the shell I get this error:
[HPM] Error occurred while trying to proxy request /api/graphql from localhost:3000 to http://localhost:4040 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
Also if I try to add a new post.
Why that? How can I fix it? Thanks!

**Comment by graffaello** [comment]
I've scrolled back the console and I've found this error at the beginning of npm start:

C:\Users\raffaello\mean>npm start

> Mean@2.0.1 start C:\Users\raffaello\mean
> concurrently "npm run server:dev" "nodemon --watch server server-start.js"

[1] [nodemon] 1.12.1
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: C:\Users\raffaello\mean\server/**/*
[1] [nodemon] starting `node server-start.js`
[0]
[0] > Mean@2.0.1 server:dev C:\Users\raffaello\mean
[0] > npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/
[0]
[1] (node:2508) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[1] server started on port 4040 (development)
[1] C:\Users\raffaello\mean\server.js:38
[1]   throw new Error('unable to connect to database: ' + mongoUri);
[1]   ^
[1]
[1] Error: unable to connect to database: mongodb://localhost/new-mean
[1]     at NativeConnection.<anonymous> (C:/Users/raffaello/mean/server.js:22:9)
[1]     at emitOne (events.js:96:13)
[1]     at NativeConnection.emit (events.js:188:7)
[1]     at Immediate.<anonymous> (C:\Users\raffaello\mean\node_modules\mongoose\lib\connection.js:325:19)
[1]     at runCallback (timers.js:672:20)
[1]     at tryOnImmediate (timers.js:645:5)
[1]     at processImmediate [as _immediateCallback] (timers.js:617:5)
[1] [nodemon] app crashed - waiting for file changes before starting...
-----------------------------

It looks like it's unable  to connect to database

**Comment by graffaello** [comment]
Maybe I got it.
I had to launch MongoDB separately, pointing at a data folder under "mean" folder.
Let's keep on testing...

**Comment by chanakaDe** [comment]
@graffaello  Did you config MongoDB instance properly ? If there are any issues on your local mongo, please try mLab free mongodb instance and try it. For many users, it worked. So then you can fix issues in your local mongo.

**Comment by graffaello** [comment]
Hi @chanakaDe 
everything looks going fine now. I'm just moving the first steps.
Thanks!

**Comment by chanakaDe** [comment]
@graffaello  Ok buddy. Feel free to ask anything anytime 👍
