### ISSUE TITLE
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/linnovate/innograph.git

### ISSUE THREAD

**Issue by amit-upadhyay-IT** [linnovate/mean#1858]
I am trying to scaffold my mean app using mean.io.

After cloning it whenever I am doing

`npm i`
It takes around 3-5 mins and after that it prompts this error:

```
[aupadhyay@localhost mean]$ npm i
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/linnovate/innograph.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.255.113]: errno=Connection timed out
npm ERR! github.com[1: 192.30.255.112]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aupadhyay/.npm/_logs/2017-11-24T08_32_19_213Z-debug.log
```
How to use mean.io for scaffold a mean app?

**Comment by chanakaDe** [comment]
@amit-upadhyay-IT Hi buddy, Please clean npm cache and try 'npm install'. And also please attach the complete log file. Then we can have a better look at what's going on there. I re-installed full mean into one of my dev servers and it didn't give me such an error. Seems your network or something specified issue. With your log file, we can help you more.

**Comment by amit-upadhyay-IT** [comment]
Below is the contents of the log file:


```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i' ]
2 info using npm@5.5.1
3 info using node@v8.6.0
4 verbose npm-session 18cb45928f4ed00a
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall Mean@2.0.1
7 info lifecycle Mean@2.0.1~preinstall: Mean@2.0.1
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly fetchPackageMetaData error for innograph@git://github.com/linnovate/innograph.git#881713e7c33ac8d2aa0ce4977ee97d2a648795e8 Error while executing:
13 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t git://github.com/linnovate/innograph.git
13 silly fetchPackageMetaData
13 silly fetchPackageMetaData fatal: unable to connect to github.com:
13 silly fetchPackageMetaData github.com[0: 192.30.255.113]: errno=Connection timed out
13 silly fetchPackageMetaData github.com[1: 192.30.255.112]: errno=Connection timed out
13 silly fetchPackageMetaData
13 silly fetchPackageMetaData
13 silly fetchPackageMetaData exited with error code: 128
14 verbose stack Error: exited with error code: 128
14 verbose stack     at ChildProcess.onexit (/usr/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
15 verbose cwd /home/aupadhyay/mean
16 verbose Linux 4.13.5-200.fc26.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
18 verbose node v8.6.0
19 verbose npm  v5.5.1
20 error Error while executing:
20 error /usr/bin/git ls-remote -h -t git://github.com/linnovate/innograph.git
20 error
20 error fatal: unable to connect to github.com:
20 error github.com[0: 192.30.255.113]: errno=Connection timed out
20 error github.com[1: 192.30.255.112]: errno=Connection timed out
20 error
20 error
20 error exited with error code: 128
21 verbose exit [ 1, true ]
```

**Comment by amit-upadhyay-IT** [comment]
@chanakaDe yes, it's solved now, my college firewall doesn't allow me to use git://protocol (some dependencies were using that protocol)

Thank you for your support :+1:
