### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by RevealedFrom** [linnovate/mean#1885]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report

* **What is the current behavior?**
I ran the three-line commands:

 $ git clone https://github.com/linnovate/mean.git
 $ cd mean
 $ npm install && npm start

A web site runs at localhost:3000, It sorts of runs fine but I am unable to confirm as I don't know what the web site should be behaving.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
- Windows 10 running in VS Code
- Angular version: 2.0.0-beta.X
- Browser:  Chrome XX

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

In the DEBUG CONSOLE, I get the following:

    Debugging with legacy protocol because Node.js v6.9.2 was detected.
    'C:\Program Files\nodejs\node.exe' --nolazy --debug-brk=40203 server.js ${max_old_space_size:4000}  
    Debugger listening on [::]:40203
    D:\Documents\Node.js\mean\server.js:1
    (function (exports, require, module, __filename, __dirname) { import mongoose from 'mongoose';
                                                                  ^^^^^^

    SyntaxError: Unexpected token import
        at Object.exports.runInThisContext (vm.js:76:16)
        at Module._compile (module.js:542:28)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)

**Comment by feenr** [comment]
Not sure why this would be happening to you, but I have found that you will get this error if babel has not already been included in the first js file which you execute, and the import statement only works in subsequent require statements.

`npm start` should call server-start.js which takes care of this.
