### ISSUE TITLE
MEAN installation error on 98c57b99f2722263898ba4fce07ef8f0f14eb65b

### ISSUE THREAD

**Issue by joseandrespena** [linnovate/mean#1892]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a Bug.

* **What is the current behavior?**
I just tried to install MEAN, following usual commands 
git clone --depth 1 https://github.com/linnovate/mean.git  
 cd mean
 npm install  
 npm start  
but failed the installation with a long error I have no idea what is the error: 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Installation(obvious)

* **What is the motivation / use case for changing the behavior?**
is a critical error

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/josepen/Development/mean/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/josepen/Development/mean/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/josepen/Development/mean/node_modules/node-sass
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-universal@2.0.11 requires a peer of zone.js@~0.6.21 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/josepen/.npm/_logs/2018-05-17T05_35_32_184Z-debug.log

I did a search on google...
seems like the problem is known... but fixed? I don't think so... wtf... I'm stuck, I was trying MEAN for first time... couldn't even install it!!! ... This is urgent.. thanks!

**Comment by feenr** [comment]
Is there anything helpful in that log,  /Users/josepen/.npm/_logs/2018-05-17T05_35_32_184Z-debug.log? 
Can you try npm-install node-sass@4.5.3 and see if it gives the same failure?

**Comment by joseandrespena** [comment]
Done seems like it install but dependencies are not cycling resolved, therefore keeps displaying the required dependencies to be install manually:
nstalled to /Users/josepen/Development/mean/node_modules/node-sass/vendor/darwin-x64-64/binding.node
npm WARN @angular/animations@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/common@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@4.4.4 requires a peer of zone.js@^0.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@4.3.6 requires a peer of @angular/core@4.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-universal@2.0.11 requires a peer of zone.js@~0.6.21 but none is installed. You must install peer dependencies yourself.
npm WARN preboot@5.0.0-rc.10 requires a peer of zone.js@^0.8.0 but none is installed. You must install peer dependencies yourself

**Comment by joseandrespena** [comment]
Just a comment, but the installation of MEAN sucks honestly... I had not NPM, Mongo, etc on my machine, Mac High Sierra 10.13.4, installed them and I'm stuck fortunately I'm just researching about it, but come on!!! cd mean, npm install, and bummmm there you are stuck...

**Comment by xavidram** [comment]
Fresh installed my Macbook Air to OSX 10.13.4. Clean installed Nodejs 8.11.3, npm version: 5.7.1, and installed MongoDB and made sure MongoDb was running properly locally. Went through the setup for the Mean stack and it worked out of the box. From the error you placed, it seems that you are having issues with node-gyp. Make sure you follow https://github.com/nodejs/node-gyp to set up node-gyp and make sure it is working properly so that it compiles the binaries for the project.
