### ISSUE TITLE
 Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by d668** [linnovate/mean#1913]
```
osboxes@osboxes:~/pr$ git clone https://github.com/linnovate/mean.git
Cloning into 'mean'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16224 (delta 8), reused 9 (delta 3), pack-reused 16205
Receiving objects: 100% (16224/16224), 7.93 MiB | 79.00 KiB/s, done.
Resolving deltas: 100% (9019/9019), done.
osboxes@osboxes:~/pr$ cd mean/
osboxes@osboxes:~/pr/mean$ npm i
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osboxes/.npm/_logs/2018-10-23T09_52_06_997Z-debug.log
osboxes@osboxes:~/pr/mean$ 

```

**Comment by intergleam** [comment]
### /home/osboxes/.npm/_logs/2018-10-23T09_52_06_997Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose npm-session 48caa83c0d41dc94
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall mean@2.0.1
7 info lifecycle mean@2.0.1~preinstall: mean@2.0.1
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 31ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2farchitect 1016ms
16 silly pacote version manifest for @angular-devkit/architect@0.7.0-rc.0 fetched in 1032ms
17 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fcore 412ms
18 silly pacote version manifest for @angular-devkit/core@0.7.0-rc.0 fetched in 420ms
19 http fetch GET 200 https://registry.npmjs.org/ajv 294ms
20 silly pacote version manifest for ajv@6.4.0 fetched in 302ms
21 http fetch GET 200 https://registry.npmjs.org/punycode 234ms
22 silly pacote version manifest for punycode@2.1.1 fetched in 239ms
23 http fetch GET 200 https://registry.npmjs.org/rxjs 348ms
24 silly pacote version manifest for rxjs@6.2.1 fetched in 355ms
25 http fetch GET 200 https://registry.npmjs.org/uri-js 137ms
26 silly pacote version manifest for uri-js@3.0.2 fetched in 159ms
27 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-angular 276ms
28 silly pacote version manifest for @angular-devkit/build-angular@0.7.0-rc.0 fetched in 320ms
29 silly pacote version manifest for @angular-devkit/core@0.7.0-rc.0 fetched in 1ms
30 silly pacote version manifest for ajv@6.4.0 fetched in 1ms
31 http fetch GET 200 https://registry.npmjs.org/chalk 132ms
32 silly pacote version manifest for chalk@2.4.1 fetched in 146ms
33 http fetch GET 200 https://registry.npmjs.org/file-loader 267ms
34 silly pacote version manifest for file-loader@1.1.11 fetched in 271ms
35 http fetch GET 200 https://registry.npmjs.org/postcss 275ms
36 silly pacote version manifest for postcss@6.0.22 fetched in 285ms
37 http fetch GET 200 https://registry.npmjs.org/source-map 163ms
38 silly pacote version manifest for source-map@0.6.1 fetched in 176ms
39 silly pacote version manifest for punycode@2.1.1 fetched in 4ms
40 silly pacote version manifest for rxjs@6.2.1 fetched in 8ms
41 http fetch GET 200 https://registry.npmjs.org/schema-utils 174ms
42 silly pacote version manifest for schema-utils@0.4.5 fetched in 186ms
43 silly pacote version manifest for ajv@6.5.1 fetched in 5ms
44 http fetch GET 200 https://registry.npmjs.org/fast-deep-equal 137ms
45 silly pacote version manifest for fast-deep-equal@2.0.1 fetched in 141ms
46 http fetch GET 200 https://registry.npmjs.org/json-schema-traverse 143ms
47 silly pacote version manifest for json-schema-traverse@0.4.1 fetched in 147ms
48 silly pacote version manifest for uri-js@4.2.2 fetched in 5ms
49 silly pacote version manifest for uri-js@3.0.2 fetched in 2ms
50 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-optimizer 459ms
51 silly pacote version manifest for @angular-devkit/build-optimizer@0.7.0-rc.0 fetched in 468ms
52 http fetch GET 200 https://registry.npmjs.org/typescript 4522ms
53 silly pacote version manifest for typescript@2.9.2 fetched in 4567ms
54 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-webpack 223ms
55 silly pacote version manifest for @angular-devkit/build-webpack@0.7.0-rc.0 fetched in 234ms
56 silly pacote version manifest for @angular-devkit/core@0.7.0-rc.0 fetched in 6ms
57 silly pacote version manifest for ajv@6.4.0 fetched in 5ms
58 silly pacote version manifest for punycode@2.1.1 fetched in 6ms
59 silly pacote version manifest for rxjs@6.2.1 fetched in 4ms
60 silly pacote version manifest for uri-js@3.0.2 fetched in 2ms
61 silly pacote version manifest for @angular-devkit/core@0.6.8 fetched in 5ms
62 silly pacote version manifest for ajv@6.4.0 fetched in 16ms
63 silly pacote version manifest for punycode@2.1.1 fetched in 3ms
64 silly pacote version manifest for rxjs@6.2.1 fetched in 3ms
65 silly pacote version manifest for uri-js@3.0.2 fetched in 1ms
66 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fschematics 421ms
67 silly pacote version manifest for @angular-devkit/schematics@0.6.8 fetched in 435ms
68 silly pacote version manifest for rxjs@6.2.1 fetched in 3ms
69 http fetch GET 200 https://registry.npmjs.org/@angular%2fanimations 421ms
70 silly pacote version manifest for @angular/animations@6.0.3 fetched in 431ms
71 http fetch GET 200 https://registry.npmjs.org/@angular%2fcdk 533ms
72 silly pacote version manifest for @angular/cdk@6.3.0 fetched in 542ms
73 http fetch GET 200 https://registry.npmjs.org/@angular%2fcli 839ms
74 silly pacote version manifest for @angular/cli@6.0.8 fetched in 855ms
75 silly pacote version manifest for @angular-devkit/architect@0.6.8 fetched in 3ms
76 silly pacote version manifest for rxjs@6.2.1 fetched in 2ms
77 http fetch GET 200 https://registry.npmjs.org/@angular%2fcommon 345ms
78 silly pacote version manifest for @angular/common@6.0.3 fetched in 352ms
79 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler 283ms
80 silly pacote version manifest for @angular/compiler@6.0.3 fetched in 288ms
81 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler-cli 423ms
82 silly pacote version manifest for @angular/compiler-cli@6.0.3 fetched in 428ms
83 http fetch GET 200 https://registry.npmjs.org/chokidar 193ms
84 http fetch GET 200 https://registry.npmjs.org/chokidar/-/chokidar-1.7.0.tgz 161ms
85 silly pacote version manifest for chokidar@1.7.0 fetched in 361ms
86 http fetch GET 200 https://registry.npmjs.org/@angular%2fcore 333ms
87 silly pacote version manifest for @angular/core@6.0.3 fetched in 338ms
88 http fetch GET 200 https://registry.npmjs.org/@angular%2fflex-layout 256ms
89 silly pacote version manifest for @angular/flex-layout@6.0.0-beta.16 fetched in 264ms
90 http fetch GET 200 https://registry.npmjs.org/@angular%2fforms 347ms
91 silly pacote version manifest for @angular/forms@6.0.3 fetched in 355ms
92 http fetch GET 200 https://registry.npmjs.org/@angular%2fhttp 313ms
93 silly pacote version manifest for @angular/http@6.0.3 fetched in 322ms
94 http fetch GET 200 https://registry.npmjs.org/@angular%2flanguage-service 378ms
95 silly pacote version manifest for @angular/language-service@6.0.3 fetched in 387ms
96 http fetch GET 200 https://registry.npmjs.org/@angular%2fmaterial 280ms
97 silly pacote version manifest for @angular/material@6.3.0 fetched in 286ms
98 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser 484ms
99 silly pacote version manifest for @angular/platform-browser@6.0.3 fetched in 494ms
100 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser-dynamic 421ms
101 silly pacote version manifest for @angular/platform-browser-dynamic@6.0.3 fetched in 436ms
102 http fetch GET 200 https://registry.npmjs.org/@angular%2frouter 383ms
103 silly pacote version manifest for @angular/router@6.0.3 fetched in 437ms
104 http fetch GET 200 https://registry.npmjs.org/@babel%2fruntime 238ms
105 silly pacote version manifest for @babel/runtime@7.0.0 fetched in 243ms
106 http fetch GET 200 https://registry.npmjs.org/regenerator-runtime 151ms
107 silly pacote version manifest for regenerator-runtime@0.12.1 fetched in 154ms
108 http fetch GET 200 https://registry.npmjs.org/@material-ui%2fcore 334ms
109 silly pacote version manifest for @material-ui/core@3.1.0 fetched in 337ms
110 http fetch GET 200 https://registry.npmjs.org/loose-envify 130ms
111 silly pacote version manifest for loose-envify@1.3.1 fetched in 132ms
112 http fetch GET 200 https://registry.npmjs.org/warning 161ms
113 silly pacote version manifest for warning@4.0.2 fetched in 164ms
114 http fetch GET 200 https://registry.npmjs.org/@material-ui%2ficons 244ms
115 silly pacote version manifest for @material-ui/icons@3.0.1 fetched in 247ms
116 http fetch GET 200 https://registry.npmjs.org/recompose 167ms
117 silly pacote version manifest for recompose@0.29.0 fetched in 170ms
118 http fetch GET 200 https://registry.npmjs.org/@ngtools%2fwebpack 415ms
119 silly pacote version manifest for @ngtools/webpack@6.1.0-rc.0 fetched in 420ms
120 silly pacote version manifest for @angular-devkit/core@0.7.0-rc.0 fetched in 1ms
121 silly pacote version manifest for ajv@6.4.0 fetched in 6ms
122 silly pacote version manifest for punycode@2.1.1 fetched in 2ms
123 silly pacote version manifest for rxjs@6.2.1 fetched in 1ms
124 silly pacote version manifest for uri-js@3.0.2 fetched in 1ms
125 http fetch GET 200 https://registry.npmjs.org/@schematics%2fangular 371ms
126 silly pacote version manifest for @schematics/angular@0.6.8 fetched in 379ms
127 http fetch GET 200 https://registry.npmjs.org/@schematics%2fupdate 465ms
128 silly pacote version manifest for @schematics/update@0.6.8 fetched in 469ms
129 silly pacote version manifest for rxjs@6.2.1 fetched in 1ms
130 http fetch GET 200 https://registry.npmjs.org/@types%2fgoogle-maps 157ms
131 http fetch GET 200 https://registry.npmjs.org/@types/google-maps/-/google-maps-3.2.0.tgz 159ms
132 silly pacote version manifest for @types/google-maps@3.2.0 fetched in 330ms
133 http fetch GET 200 https://registry.npmjs.org/@types%2fgooglemaps 147ms
134 silly pacote version manifest for @types/googlemaps@3.30.13 fetched in 151ms
135 http fetch GET 200 https://registry.npmjs.org/@types%2fjasmine 131ms
136 silly pacote version manifest for @types/jasmine@2.8.8 fetched in 134ms
137 http fetch GET 200 https://registry.npmjs.org/@types%2fjasminewd2 156ms
138 http fetch GET 200 https://registry.npmjs.org/@types/jasminewd2/-/jasminewd2-2.0.3.tgz 173ms
139 silly pacote version manifest for @types/jasminewd2@2.0.3 fetched in 336ms
140 http fetch GET 200 https://registry.npmjs.org/@types%2fjss 165ms
141 silly pacote version manifest for @types/jss@9.5.6 fetched in 169ms
142 http fetch GET 200 https://registry.npmjs.org/@types%2fmarkerclustererplus 164ms
143 http fetch GET 200 https://registry.npmjs.org/@types/markerclustererplus/-/markerclustererplus-2.1.33.tgz 200ms
144 silly pacote version manifest for @types/markerclustererplus@2.1.33 fetched in 369ms
145 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 735ms
146 silly pacote version manifest for @types/node@10.3.4 fetched in 746ms
147 http fetch GET 200 https://registry.npmjs.org/@types%2fprop-types 133ms
148 silly pacote version manifest for @types/prop-types@15.5.5 fetched in 147ms
149 http fetch GET 200 https://registry.npmjs.org/@types%2fq 137ms
150 http fetch GET 200 https://registry.npmjs.org/@types/q/-/q-0.0.32.tgz 153ms
151 silly pacote version manifest for @types/q@0.0.32 fetched in 293ms
152 http fetch GET 200 https://registry.npmjs.org/@types%2freact 279ms
153 silly pacote version manifest for @types/react@16.4.14 fetched in 287ms
154 http fetch GET 200 https://registry.npmjs.org/@types%2freact-transition-group 114ms
155 silly pacote version manifest for @types/react-transition-group@2.0.14 fetched in 117ms
156 http fetch GET 200 https://registry.npmjs.org/@types%2fselenium-webdriver 179ms
157 http fetch GET 200 https://registry.npmjs.org/@types/selenium-webdriver/-/selenium-webdriver-2.53.43.tgz 182ms
158 silly pacote version manifest for @types/selenium-webdriver@2.53.43 fetched in 368ms
159 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fast 295ms
160 silly pacote version manifest for @webassemblyjs/ast@1.4.3 fetched in 298ms
161 http fetch GET 200 https://registry.npmjs.org/debug 280ms
162 http fetch GET 200 https://registry.npmjs.org/debug/-/debug-3.1.0.tgz 138ms
163 silly pacote version manifest for debug@3.1.0 fetched in 423ms
164 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2ffloating-point-hex-parser 239ms
165 silly pacote version manifest for @webassemblyjs/floating-point-hex-parser@1.4.3 fetched in 242ms
166 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-buffer 249ms
167 silly pacote version manifest for @webassemblyjs/helper-buffer@1.4.3 fetched in 252ms
168 silly pacote version manifest for debug@3.1.0 fetched in 1ms
169 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-code-frame 322ms
170 silly pacote version manifest for @webassemblyjs/helper-code-frame@1.4.3 fetched in 325ms
171 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-fsm 350ms
172 silly pacote version manifest for @webassemblyjs/helper-fsm@1.4.3 fetched in 357ms
173 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-wasm-bytecode 359ms
174 silly pacote version manifest for @webassemblyjs/helper-wasm-bytecode@1.4.3 fetched in 373ms
175 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fhelper-wasm-section 385ms
176 silly pacote version manifest for @webassemblyjs/helper-wasm-section@1.4.3 fetched in 398ms
177 silly pacote version manifest for debug@3.1.0 fetched in 2ms
178 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fleb128 244ms
179 silly pacote version manifest for @webassemblyjs/leb128@1.4.3 fetched in 251ms
180 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fvalidation 351ms
181 silly pacote version manifest for @webassemblyjs/validation@1.4.3 fetched in 354ms
182 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-edit 341ms
183 silly pacote version manifest for @webassemblyjs/wasm-edit@1.4.3 fetched in 345ms
184 silly pacote version manifest for debug@3.1.0 fetched in 1ms
185 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-gen 412ms
186 silly pacote version manifest for @webassemblyjs/wasm-gen@1.4.3 fetched in 437ms
187 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-opt 558ms
188 silly pacote version manifest for @webassemblyjs/wasm-opt@1.4.3 fetched in 562ms
189 silly pacote version manifest for debug@3.1.0 fetched in 1ms
190 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwasm-parser 535ms
191 silly pacote version manifest for @webassemblyjs/wasm-parser@1.4.3 fetched in 541ms
192 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwast-parser 549ms
193 silly pacote version manifest for @webassemblyjs/wast-parser@1.4.3 fetched in 553ms
194 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwast-printer 559ms
195 silly pacote version manifest for @webassemblyjs/wast-printer@1.4.3 fetched in 565ms
196 http fetch GET 200 https://registry.npmjs.org/abab 207ms
197 silly pacote version manifest for abab@1.0.4 fetched in 212ms
198 http fetch GET 200 https://registry.npmjs.org/abbrev 229ms
199 silly pacote version manifest for abbrev@1.1.1 fetched in 235ms
200 http fetch GET 200 https://registry.npmjs.org/accepts 206ms
201 silly pacote version manifest for accepts@1.3.5 fetched in 212ms
202 http fetch GET 200 https://registry.npmjs.org/acorn 255ms
203 http fetch GET 200 https://registry.npmjs.org/acorn/-/acorn-4.0.13.tgz 489ms
204 silly pacote version manifest for acorn@4.0.13 fetched in 755ms
205 http fetch GET 200 https://registry.npmjs.org/acorn-dynamic-import 221ms
206 http fetch GET 200 https://registry.npmjs.org/acorn-dynamic-import/-/acorn-dynamic-import-3.0.0.tgz 165ms
207 silly pacote version manifest for acorn-dynamic-import@3.0.0 fetched in 392ms
208 silly pacote version manifest for acorn@5.7.1 fetched in 8ms
209 http fetch GET 200 https://registry.npmjs.org/acorn-globals 222ms
210 http fetch GET 200 https://registry.npmjs.org/acorn-globals/-/acorn-globals-3.1.0.tgz 253ms
211 silly pacote version manifest for acorn-globals@3.1.0 fetched in 488ms
212 http fetch GET 200 https://registry.npmjs.org/acorn-jsx 138ms
213 http fetch GET 200 https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-3.0.1.tgz 278ms
214 silly pacote version manifest for acorn-jsx@3.0.1 fetched in 423ms
215 http fetch GET 200 https://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz 428ms
216 silly pacote version manifest for acorn@3.3.0 fetched in 431ms
217 http fetch GET 200 https://registry.npmjs.org/address 152ms
218 silly pacote version manifest for address@1.0.3 fetched in 155ms
219 http fetch GET 200 https://registry.npmjs.org/addressparser 144ms
220 silly pacote version manifest for addressparser@1.0.1 fetched in 147ms
221 http fetch GET 200 https://registry.npmjs.org/adm-zip 177ms
222 silly pacote version manifest for adm-zip@0.4.11 fetched in 179ms
223 http fetch GET 200 https://registry.npmjs.org/after 148ms
224 silly pacote version manifest for after@0.8.2 fetched in 152ms
225 http fetch GET 200 https://registry.npmjs.org/agent-base 155ms
226 silly pacote version manifest for agent-base@4.2.0 fetched in 158ms
227 http fetch GET 200 https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz 1374ms
228 silly pacote version manifest for ajv@5.5.2 fetched in 1384ms
229 http fetch GET 200 https://registry.npmjs.org/ajv-keywords 240ms
230 silly pacote version manifest for ajv-keywords@3.2.0 fetched in 268ms
231 timing stage:rollbackFailedOptional Completed in 0ms
232 timing stage:runTopLevelLifecycles Completed in 34939ms
233 silly saveTree mean@2.0.1
233 silly saveTree ├─┬ @angular-devkit/build-angular@0.7.0-rc.0
233 silly saveTree │ ├─┬ @angular-devkit/architect@0.7.0-rc.0
233 silly saveTree │ │ ├─┬ @angular-devkit/core@0.7.0-rc.0
233 silly saveTree │ │ │ ├─┬ ajv@6.4.0
233 silly saveTree │ │ │ │ └─┬ uri-js@3.0.2
233 silly saveTree │ │ │ │   └── punycode@2.1.1
233 silly saveTree │ │ │ └── rxjs@6.2.1
233 silly saveTree │ │ └── rxjs@6.2.1
233 silly saveTree │ ├─┬ @angular-devkit/build-optimizer@0.7.0-rc.0
233 silly saveTree │ │ └── typescript@2.9.2
233 silly saveTree │ ├─┬ @angular-devkit/build-webpack@0.7.0-rc.0
233 silly saveTree │ │ ├─┬ @angular-devkit/core@0.7.0-rc.0
233 silly saveTree │ │ │ ├─┬ ajv@6.4.0
233 silly saveTree │ │ │ │ └─┬ uri-js@3.0.2
233 silly saveTree │ │ │ │   └── punycode@2.1.1
233 silly saveTree │ │ │ └── rxjs@6.2.1
233 silly saveTree │ │ └── rxjs@6.2.1
233 silly saveTree │ ├─┬ @angular-devkit/core@0.7.0-rc.0
233 silly saveTree │ │ ├─┬ ajv@6.4.0
233 silly saveTree │ │ │ └─┬ uri-js@3.0.2
233 silly saveTree │ │ │   └── punycode@2.1.1
233 silly saveTree │ │ └── rxjs@6.2.1
233 silly saveTree │ ├─┬ @ngtools/webpack@6.1.0-rc.0
233 silly saveTree │ │ └─┬ @angular-devkit/core@0.7.0-rc.0
233 silly saveTree │ │   ├─┬ ajv@6.4.0
233 silly saveTree │ │   │ └─┬ uri-js@3.0.2
233 silly saveTree │ │   │   └── punycode@2.1.1
233 silly saveTree │ │   └── rxjs@6.2.1
233 silly saveTree │ ├── ajv@6.4.0
233 silly saveTree │ ├─┬ file-loader@1.1.11
233 silly saveTree │ │ └─┬ schema-utils@0.4.5
233 silly saveTree │ │   ├── ajv-keywords@3.2.0
233 silly saveTree │ │   └─┬ ajv@6.5.1
233 silly saveTree │ │     ├── fast-deep-equal@2.0.1
233 silly saveTree │ │     ├── json-schema-traverse@0.4.1
233 silly saveTree │ │     └── uri-js@4.2.2
233 silly saveTree │ ├─┬ postcss@6.0.22
233 silly saveTree │ │ ├── chalk@2.4.1
233 silly saveTree │ │ └── source-map@0.6.1
233 silly saveTree │ └── rxjs@6.2.1
233 silly saveTree ├── @angular/animations@6.0.3
233 silly saveTree ├── @angular/cdk@6.3.0
233 silly saveTree ├─┬ @angular/cli@6.0.8
233 silly saveTree │ ├─┬ @angular-devkit/architect@0.6.8
233 silly saveTree │ │ ├─┬ @angular-devkit/core@0.6.8
233 silly saveTree │ │ │ ├─┬ ajv@6.4.0
233 silly saveTree │ │ │ │ └─┬ uri-js@3.0.2
233 silly saveTree │ │ │ │   └── punycode@2.1.1
233 silly saveTree │ │ │ └── rxjs@6.2.1
233 silly saveTree │ │ └── rxjs@6.2.1
233 silly saveTree │ ├── @angular-devkit/core@0.6.8
233 silly saveTree │ ├─┬ @angular-devkit/schematics@0.6.8
233 silly saveTree │ │ └── rxjs@6.2.1
233 silly saveTree │ ├── @schematics/angular@0.6.8
233 silly saveTree │ ├─┬ @schematics/update@0.6.8
233 silly saveTree │ │ └── rxjs@6.2.1
233 silly saveTree │ └── rxjs@6.2.1
233 silly saveTree ├── @angular/common@6.0.3
233 silly saveTree ├─┬ @angular/compiler-cli@6.0.3
233 silly saveTree │ └── chokidar@1.7.0
233 silly saveTree ├── @angular/compiler@6.0.3
233 silly saveTree ├── @angular/core@6.0.3
233 silly saveTree ├── @angular/flex-layout@6.0.0-beta.16
233 silly saveTree ├── @angular/forms@6.0.3
233 silly saveTree ├── @angular/http@6.0.3
233 silly saveTree ├── @angular/language-service@6.0.3
233 silly saveTree ├── @angular/material@6.3.0
233 silly saveTree ├── @angular/platform-browser-dynamic@6.0.3
233 silly saveTree ├── @angular/platform-browser@6.0.3
233 silly saveTree ├── @angular/router@6.0.3
233 silly saveTree ├── @types/jasmine@2.8.8
233 silly saveTree ├── @types/jasminewd2@2.0.3
233 silly saveTree └── @types/node@10.3.4
234 verbose stack TypeError: Cannot read property 'match' of undefined
234 verbose stack     at tarballToVersion (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
234 verbose stack     at inflatableChild (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
234 verbose stack     at BB.each (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
234 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
234 verbose stack     at Object.gotValue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
234 verbose stack     at Object.gotAccum (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
234 verbose stack     at Object.tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
234 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
234 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
234 verbose stack     at Promise._settlePromiseCtx (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
234 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
234 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
234 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
234 verbose stack     at runCallback (timers.js:705:18)
234 verbose stack     at tryOnImmediate (timers.js:676:5)
234 verbose stack     at processImmediate (timers.js:658:5)
235 verbose cwd /home/osboxes/pr/mean
236 verbose Linux 4.15.0-36-generic
237 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
238 verbose node v10.12.0
239 verbose npm  v6.4.1
240 error Cannot read property 'match' of undefined
241 verbose exit [ 1, true ]
```

**Comment by intergleam** [comment]
```
osboxes@osboxes:~/pr/mean$ node -v
v10.12.0
osboxes@osboxes:~/pr/mean$ npm -v
6.4.1
```

**Comment by intergleam** [comment]
same on Winodws

**Comment by JayendraGothi** [comment]
Facing same issue.. on MAC OS.. node version 10.11.0, npm version 6.4.1

**Comment by 756dk** [comment]
Removing **npm-shrinkwrap.json** file. Worked for me on Windows.

**Comment by liorkesos** [comment]
What do you mean renaming the shrinkwrap what did you rename it to?

**Comment by 756dk** [comment]
@liorkesos  I Renamed it too - npm-shrinkwrap.json-- 
and then Run npm install. It worked for me.

**Comment by vinothkaambli** [comment]
@756dk  why we should change the name as - npm-shrinkwrap.json--

**Comment by intergleam** [comment]
renaming is some ugly workaround, devs need to address this issue. Projects doesn't start anyway, see [next issue](https://github.com/linnovate/mean/issues/1914). Project seem abandoned. May be devs better close it down not to waste people's time?

**Comment by intergleam** [comment]
http://mean.io/ "suggest" `npm install && npm start`

**Comment by intergleam** [comment]
the website is still wrong

**Comment by HasanAliKaraca** [comment]
Issue needs fix but closed. Please change it's status open or fix website
