### ISSUE TITLE
i got error when i run npm run dev

### ISSUE THREAD

**Issue by mwas66** [linnovate/mean#1921]
C:\Users\mwas\Desktop\project\noderest api\index.js:8
sever.listern(config.PORT, () => {
^

ReferenceError: sever is not defined
    at Object.<anonymous> (C:\Users\mwas\Desktop\project\noderest api\index.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by feenr** [comment]
Are you using an old version of this project? It currently doesn't define an npm script named dev. I know the older version did.

**Comment by mwas66** [comment]
I was following a tutorial on YouTube

**Comment by liorkesos** [comment]
closing
