### ISSUE TITLE
Update to angular 7

### ISSUE THREAD

**Issue by JeromeDesseaux** [linnovate/mean#1939]
Hi and thanks for you work! 

I can't update Angular 6 to 7 following the Angular's team rules. I get the following error : 

`C:\Users\jerome\Desktop\mean\src\app (master -> origin)
λ ng update @angular/cli @angular/core
Your global Angular CLI version (7.1.4) is greater than your local
version (6.0.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Current active project is ambiguous (angular-material-e2e) using path: '/C/Users/jerome/Desktop/mean/src/app'
Error: Current active project is ambiguous (angular-material-e2e) using path: '/C/Users/jerome/Desktop/mean/src/app'
    at Workspace.getProjectByPath (C:\Users\jerome\Desktop\mean\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\workspace\workspace.js:150:23)
    at Object.getPackageManager (C:\Users\jerome\Desktop\mean\node_modules\@angular\cli\utilities\config.js:97:35)
    at UpdateCommand.runSchematic (C:\Users\jerome\Desktop\mean\node_modules\@angular\cli\models\schematic-command.js:74:38)
    at UpdateCommand.<anonymous> (C:\Users\jerome\Desktop\mean\node_modules\@angular\cli\commands\update.js:70:25)
    at Generator.next (<anonymous>)
    at C:\Users\jerome\Desktop\mean\node_modules\@angular\cli\commands\update.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\jerome\Desktop\mean\node_modules\@angular\cli\commands\update.js:3:12)
    at UpdateCommand.run (C:\Users\jerome\Desktop\mean\node_modules\@angular\cli\commands\update.js:69:16)
    at C:\Users\jerome\Desktop\mean\node_modules\@angular\cli\models\command-runner.js:278:30`

In any directory I tried. 

Any clue?

**Comment by andrey1103** [comment]
Uninstall old angular cli and after that install the new one.
