### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by Kizzo29** [linnovate/mean#1970]

**Comment by Kizzo29** [comment]
![image](https://user-images.githubusercontent.com/60519215/74106347-e34a3b00-4b6e-11ea-88bc-9f3e169ae73f.png)

**Comment by Kizzo29** [comment]
tried npm install, tried restarting the server but still getting same output

**Comment by blyssy** [comment]
/home/blyssy/pts_development/PTS/node_modules/q/q.js:155
                throw e;
                ^
MissingSchemaError: Schema hasn't been registered for model "Customers".
Use mongoose.model(name, schema)
    at MissingSchemaError
(/home/blyssy/pts_development/PTS/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at Mongoose.model
(/home/blyssy/pts_development/PTS/node_modules/mongoose/lib/index.js:391:13)
    at Object.<anonymous>
(/home/blyssy/pts_development/PTS/packages/custom/accounts-receivable/server/controllers/tradeInvoices.js:11:26)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
(/home/blyssy/pts_development/PTS/packages/custom/accounts-receivable/server/routes/tradeInvoices.js:4:21)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)

**Comment by anushkabahuguna** [comment]
@Kizzo29 
`pkill -f node`

**Comment by arturovt** [comment]
Hey @Kizzo29 

Your error means that the port number, you're trying to use, _is already in use_.

**Comment by kavatishankar** [comment]
try to change port number use different local host

**Comment by Mrlinjiapeng** [comment]
i found to restart the vscode clould work either,but i don t know why LOL

**Comment by Mrlinjiapeng** [comment]
i found to restart the vscode could work, but i dont know why LOL
