### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting... 

### ISSUE THREAD

**Issue by 13709656857** [linnovate/mean#1974]
+ nodemon@2.0.3
updated 1 package in 14.133s
PS C:\Users\rotash\Desktop\4-natours> nodemon app.js        
[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
C:\Users\rotash\Desktop\4-natours\app.js:16
    Console.log(`App running on port ${port}...`);
    ^

ReferenceError: Console is not defined
    at Server.<anonymous> (C:\Users\rotash\Desktop\4-natours\app.js:16:5)
    at Object.onceWrapper (events.js:417:28)
    at Server.emit (events.js:311:20)
    at emitListeningNT (net.js:1343:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)[nodemon] app crashed - waiting for file changes before starting...
  i got this when i trying to connect server with postman app

**Comment by OmPals** [comment]
It must be "console.log" and not "Console.log".
