### ISSUE TITLE
Error: Cannot find module 'npm'

### ISSUE THREAD

**Issue by pak1989** [linnovate/mean#1984]
I've been trying to use this cli on arch linux manjaro.

$ npm -v
6.14.5
$ node -v
v12.16.3

mean init command is fine, the projects gets generated.

Every other command goes in error and the stack looks like this:
$ mean status
```

internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'npm'
Require stack:
- /home/pak89/.node_modules/lib/node_modules/mean-cli/lib/cli.js
- /home/pak89/.node_modules/lib/node_modules/mean-cli/bin/mean-package
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/pak89/.node_modules/lib/node_modules/mean-cli/lib/cli.js:5:7)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pak89/.node_modules/lib/node_modules/mean-cli/lib/cli.js',
    '/home/pak89/.node_modules/lib/node_modules/mean-cli/bin/mean-package'
  ]
}

```

I'm not sure but I think that it tries to import the npm module without success, because in fact the npm files are located elsewhere.

**Comment by arturovt** [comment]
You should move the issue to mean-cli repository.
