### ISSUE TITLE
Nodemon crash

### ISSUE THREAD

**Issue by mosskhinagte** [linnovate/mean#1995]
PS C:\amazona> npm start

> amazona@1.0.0 start C:\amazona
> nodemon --watch backend --exec babel-node backend/server.js

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): backend\**\*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node backend/server.js`
C:\amazona\node_modules\@babel\core\lib\config\validation\options.js:126
    throw unknownOptErr;
    ^

Error: Unknown option: .preset. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (C:\amazona\node_modules\@babel\core\lib\config\validation\options.js:124:27)
    at C:\amazona\node_modules\@babel\core\lib\config\validation\options.js:109:5
    at Array.forEach (<anonymous>)
    at validateNested (C:\amazona\node_modules\@babel\core\lib\config\validation\options.js:85:21)
    at validate (C:\amazona\node_modules\@babel\core\lib\config\validation\options.js:76:10)
    at C:\amazona\node_modules\@babel\core\lib\config\config-chain.js:189:34
    at cachedFunction (C:\amazona\node_modules\@babel\core\lib\config\caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (C:\amazona\node_modules\gensync\index.js:244:28)
    at sync (C:\amazona\node_modules\gensync\index.js:84:14) {
  code: 'BABEL_UNKNOWN_OPTION'
}
[nodemon] app crashed - waiting for file changes before starting...

Any can help me to fix the above  issue please?

**Comment by arturovt** [comment]
Hey, this project doesn't use the `babel-node` package.
