### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by fahimarefi** [linnovate/mean#2005]
Hello, I am new at all, I am practicing from some tutorial I got this error can anyone help me, please?
PS E:\bot\src> npm start

> bot@1.0.0 start E:\bot
> nodemon --exec babel-node src/server.js

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node src/server.js`
E:\bot\src\config\viewEngine.js:13
modul.exports = configViewEngin;
^

ReferenceError: modul is not defined
    at Object.<anonymous> (E:\bot\src\config\/viewEngine.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (E:\bot\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (E:\bot\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\bot\src\/server.js:4:1)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ankur2194** [comment]
Correct the spelling, it should be `module.exports` but you have wrote `modul.exports`, so it should be corrected!
