### ISSUE TITLE
Callback is not a function! issue

### ISSUE THREAD

**Issue by Umar90909** [linnovate/mean#2017]
TypeError: callback is not a function
    at Request._callback (D:\NodeTraining\web-server\src\utils\forecast.js:23:13)
    at Request.self.callback (D:\NodeTraining\web-server\node_modules\request\request.js:185:22)
    at Request.emit (node:events:369:20)
    at Request.<anonymous> (D:\NodeTraining\web-server\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:369:20)
    at IncomingMessage.<anonymous> (D:\NodeTraining\web-server\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:475:28)
    at IncomingMessage.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by arturovt** [comment]
We don't have the _forecast.js_ file in the repository.
