### ISSUE TITLE
get Username cannot be blank error when auth with google

### ISSUE THREAD

**Issue by yinzhiqiang** [linnovate/mean#289]
```
ValidationError: Username cannot be blank
    at model.Document.invalidate (/var/lib/stickshift/52f20b955973cae3bc00002d/app-root/data/645894/node_modules/mongoose/lib/document.js:1009:32)
    at /var/lib/stickshift/52f20b955973cae3bc00002d/app-root/data/645894/node_modules/mongoose/lib/document.js:958:16
    at validate (/var/lib/stickshift/52f20b955973cae3bc00002d/app-root/data/645894/node_modules/mongoose/lib/schematype.js:610:7)
    at /var/lib/stickshift/52f20b955973cae3bc00002d/app-root/data/645894/node_modules/mongoose/lib/schematype.js:627:9
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/var/lib/stickshift/52f20b955973cae3bc00002d/app-root/data/645894/node_modules/mongoose/lib/schematype.js:614:19)
    at /var/lib/stickshift/52f20b955973cae3bc00002d/app-root/data/645894/node_modules/mongoose/lib/document.js:956:9
    at process._tickCallback (node.js:415:13)
```

The bug is caused by passport-oauth-google model don't provide profile.username attribute, but in config\passport.js still use it at 
```
   // Use google strategy
    passport.use(new GoogleStrategy({
            clientID: config.google.clientID,
            clientSecret: config.google.clientSecret,
            callbackURL: config.google.callbackURL
        },
        function(accessToken, refreshToken, profile, done) {
            User.findOne({
                'google.id': profile.id
            }, function(err, user) {
                if (!user) {
                    user = new User({
                        name: profile.displayName,
                        email: profile.emails[0].value,
                        username: profile.username, //cause ValidationError
                        provider: 'google',
                        google: profile._json
                    });
                    user.save(function(err) {
                        if (err) console.log(err);
                        return done(err, user);
                    });
                } else {
                    return done(err, user);
                }
            });
        }
    ));
```

**Comment by liorkesos** [comment]
merged.
