### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by altryne** [linnovate/mean#52]
```

> mean@1.0.0 postinstall /Users/altryne/www/followme
> node_modules/bower/bin/bower install


module.js:340
    throw err;
          ^
Error: Cannot find module 'mout'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/altryne/www/followme/node_modules/bower/bin/bower:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
npm ERR! mean@1.0.0 postinstall: `node_modules/bower/bin/bower install`
npm ERR! `sh "-c" "node_modules/bower/bin/bower install"` failed with 8
npm ERR!
npm ERR! Failed at the mean@1.0.0 postinstall script.
npm ERR! This is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/bower/bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/altryne/www/followme
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/altryne/www/followme/npm-debug.log
npm ERR! not ok code 0
```

**Comment by OmarTrigui** [comment]
You have to remove the "bower" package from your node_modules folder.
