### ISSUE TITLE
when I use ui-bootstrap carousel, appear a error

### ISSUE THREAD

**Issue by arccode** [linnovate/mean#524]
TypeError: undefined is not a function
    at link (http://localhost:3000/public/system/lib/angular-bootstrap/ui-bootstrap-tpls.js:684:20)
    at http://localhost:3000/public/system/lib/angular/angular.js:6970:44
    at nodeLinkFn (http://localhost:3000/public/system/lib/angular/angular.js:6579:13)
    at delayedNodeLinkFn (http://localhost:3000/public/system/lib/angular/angular.js:6798:11)
    at compositeLinkFn (http://localhost:3000/public/system/lib/angular/angular.js:5982:15)
    at publicLinkFn (http://localhost:3000/public/system/lib/angular/angular.js:5891:30)
    at boundTranscludeFn (http://localhost:3000/public/system/lib/angular/angular.js:6005:21)
    at controllersBoundTransclude (http://localhost:3000/public/system/lib/angular/angular.js:6600:18)
    at ngRepeatAction (http://localhost:3000/public/system/lib/angular/angular.js:20084:15)
    at Object.$watchCollectionAction [as fn](http://localhost:3000/public/system/lib/angular/angular.js:12126:13) <div ng-class="{
    'active': leaving || (active &amp;&amp; !entering),
    'prev': (next || active) &amp;&amp; direction=='prev',
    'next': (next || active) &amp;&amp; direction=='next',
    'right': direction=='prev',
    'left': direction=='next'
  }" class="item text-center ng-isolate-scope" ng-transclude="" ng-repeat="slide in slides" active="slide.active">

**Comment by rnt363** [comment]
thank you SO MUCH. we just spent so much time trying t figure this out.

**Comment by fuzzybook** [comment]
.config( ['$animateProvider',
        function ($animateProvider) {
            $animateProvider.classNameFilter(/^(?:(?!carousel).)*$/);
        }])
