### ISSUE TITLE
Running with grunt got "cannot find module 'meanio'" error

### ISSUE THREAD

**Issue by shunia** [linnovate/mean#585]
Output below:

```
[root@datanode-2 17173fe]# grunt
Running "clean:0" (clean) task

Running "jshint:all" (jshint) task
>> 42 files lint free.

Running "csslint:src" (csslint) task
>> 2 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "nodemon:dev" (nodemon) task
Running "watch" task
Waiting...
[nodemon] v1.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858

module.js:340
    throw err;
          ^
Error: Cannot find module 'meanio'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/dev/17173fe/server/config/system/bootstrap.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nicesu** [comment]
I also encountered such a problem， I am a such solutions：
first: 
   update npm  ：$ npm update -g npm

second:
  Clean Cache: $ npm cache clean

laster:
  $ npm install meanio --save

**Comment by ionut-tanasa** [comment]
@nicesu your solution worked for me. thank you
