### ISSUE TITLE
App is crashing when calling the URL (bower issue)

### ISSUE THREAD

**Issue by yizhao** [linnovate/mean#718]
This issue is the same as #520 which has been closed.  To summarize, the issue is:

> If I call the url localhost:3000 the app is crashing
> 
> GET / 304 35.867 ms - -
> 
> events.js:72
> throw er; // Unhandled 'error' event
> ^
> Error: ENOENT, open '/Users/marco/bp-portal/public/system/lib/bootstrap/dist/css/bootstrap.css'
> [nodemon] app crashed - waiting for file changes before starting...

The recommended solution `node node_modules/bower/bin/bower install` fixes the problem but this happens every time a new app is created.  Is there a permanent solution?

**Comment by pointofsalehapijs** [comment]
i got error when run grunt .how do i recover error ?

C:\hapi\kiki\node_modules\meanio\node_modules\q\q.js:128
                    throw e;
                          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\hapi\kiki\packages\contrib\mean-admin\server\contr
ollers\themes.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by karguvelrajan** [comment]
I am following the same process of hosting in AWS...

When i give "npm start" the solution perfectly running, and then i try to access the AWS instance it's not reachanbel.

Then i try "node server-start.js" then try to access the AWS instance it's running the back-end alone.
