### ISSUE TITLE
Missing dependency: ms

### ISSUE THREAD

**Issue by sebdah** [linnovate/mean#755]
I get the following when initializing a new app:

    $ npm install
    $ grunt

    /Users/sebastian/tmp/additional/node_modules/meanio/node_modules/q/q.js:126
                        throw e;
                              ^
    Error: Cannot find module 'ms'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/Users/sebastian/tmp/additional/node_modules/serve-favicon/index.js:16:10)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)

Installing `ms` with `npm install ms` resolves the problem

**Comment by VikramTiwari** [comment]
Fixed in latest version. Reopen if this is encountered again.
