### ISSUE TITLE
Failed in twitter auth

### ISSUE THREAD

**Issue by AraanBranco** [linnovate/mean#870]
Whenever I try to sign up with twitter appears the following message:

```
Error: Failed to find request token in session
    at Strategy.OAuthStrategy.authenticate (/var/www/nerdtrack/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:142:54)
    at Strategy.authenticate (/var/www/nerdtrack/node_modules/passport-twitter/lib/strategy.js:85:40)
    at attempt (/var/www/nerdtrack/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/var/www/nerdtrack/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/var/www/nerdtrack/node_modules/express/lib/router/layer.js:82:5)
    at next (/var/www/nerdtrack/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/var/www/nerdtrack/node_modules/express/lib/router/route.js:81:3)
    at eval (eval at wrapHandle (/var/www/nerdtrack/node_modules/newrelic/lib/instrumentation/express.js:261:48), <anonymous>:10:19)
    at Layer.handle [as handle_request] (/var/www/nerdtrack/node_modules/express/lib/router/layer.js:82:5)
    at /var/www/nerdtrack/node_modules/express/lib/router/index.js:234:24
```

**Comment by pasupulaphani** [comment]
use 127.0.0.1 as callback url

**Comment by VikramTiwari** [comment]
If any more questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
