### ISSUE TITLE
asset.json javascript file order scrambled in /

### ISSUE THREAD

**Issue by MichaelJCole** [linnovate/mean#940]
Hi, my asset.json files are getting reordered in my / document.  Any suggestions as to why?

asset.json
```javascript
{
  "core": {
    "css": {
      "bower_components/build/css/dist.min.css": []
    },
    "js": {
      "bower_components/build/js/dist.min.js": [
        "bower_components/jquery/dist/jquery.min.js",
        "bower_components/bootstrap/dist/bootstrap.min.js",
        "bower_components/bootstrap/js/transition.js",
        "bower_components/bootstrap/js/collapse.js",
        "bower_components/bootstrap/js/dropdown.js",
        "bower_components/bootstrap/js/button.js",
        "bower_components/angular/angular.js",
        "bower_components/angular-mocks/angular-mocks.js",
        "bower_components/angular-cookies/angular-cookies.js",
        "bower_components/angular-resource/angular-resource.js",
        "bower_components/angular-ui-router/release/angular-ui-router.js",
        "bower_components/angular-bootstrap/ui-bootstrap.js",
        "bower_components/angular-bootstrap/ui-bootstrap-tpls.js"
      ]
    }
  }
}
```

My site's / document:

```html
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="https://www.facebook.com/2008/fbml" itemscope="itemscope" itemtype="http://schema.org/Product">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <title>MEAN - FullStack JS - Development - MEAN - FullStack JS - Development</title>
  ...
  <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.css">
  ...  
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body data-ng-controller="ThemeController" ng-cloak class="ng-cloak" ng-class="state">
    <div class="navbar navbar-default" data-ng-include="'/system/views/header.html'" data-role="navigation"></div>
...
</div>

  <script type="text/javascript" src="/bower_components/jquery/dist/jquery.min.js"></script>
  <script type="text/javascript" src="/bower_components/bootstrap/js/transition.js"></script>
  <script type="text/javascript" src="/bower_components/angular-bootstrap/ui-bootstrap.js"></script>
  <script type="text/javascript" src="/bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
  <script type="text/javascript" src="/bower_components/bootstrap/js/collapse.js"></script>
  <script type="text/javascript" src="/bower_components/bootstrap/js/dropdown.js"></script>
  <script type="text/javascript" src="/bower_components/bootstrap/js/button.js"></script>
  <script type="text/javascript" src="/bower_components/angular/angular.js"></script>
  <script type="text/javascript" src="/bower_components/angular-mocks/angular-mocks.js"></script>
  <script type="text/javascript" src="/bower_components/angular-cookies/angular-cookies.js"></script>
  <script type="text/javascript" src="/bower_components/angular-resource/angular-resource.js"></script>
  <script type="text/javascript" src="/bower_components/angular-ui-router/release/angular-ui-router.js"></script>
  <script type="text/javascript" src="/packages/contrib/mean-admin/public/assets/lib/ng-clip/src/ngClip.js"></script>
  <script type="text/javascript" src="/packages/contrib/mean-admin/public/assets/lib/zeroclipboard/dist/ZeroClipboard.js"></script>
  <script type="text/javascript" src="/packages/articles/public/articles.js"></script>
  <script type="text/javascript" src="/packages/theme/public/theme.js"></script>
  <script type="text/javascript" src="/packages/system/public/init.js"></script>
  <script type="text/javascript" src="/packages/system/public/system.js"></script>
  <script type="text/javascript" src="/packages/users/public/users.js"></script>
  ...
```

I think it's causing this error browser error:

```
Uncaught ReferenceError: angular is not defined ui-bootstrap.js:8 (anonymous function)
ui-bootstrap-tpls.js:8 
Uncaught ReferenceError: angular is not defined
angular.js:80 Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:modulerr] Failed to instantiate module ui.bootstrap due to:
Error: [$injector:nomod] Module 'ui.bootstrap' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.2/$injector/nomod?p0=ui.bootstrap
    at REGEX_STRING_REGEXP (http://localhost:3000/bower_components/angular/angular.js:80:12)
    at http://localhost:3000/bower_components/angular/angular.js:1764:17
    at ensure (http://localhost:3000/bower_components/angular/angular.js:1688:38)
    at module (http://localhost:3000/bower_components/angular/angular.js:1762:14)
    at http://localhost:3000/bower_components/angular/angular.js:4030:22
    at forEach (http://localhost:3000/bower_components/angular/angular.js:339:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4014:5)
    at http://localhost:3000/bower_components/angular/angular.js:4031:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:339:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4014:5)
http://errors.angularjs.org/1.3.2/$injector/modulerr?p0=ui.bootstrap&p1=Err…2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A4014%3A5)
    at REGEX_STRING_REGEXP (http://localhost:3000/bower_components/angular/angular.js:80:12)
    at http://localhost:3000/bower_components/angular/angular.js:4053:15
    at forEach (http://localhost:3000/bower_components/angular/angular.js:339:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4014:5)
    at http://localhost:3000/bower_components/angular/angular.js:4031:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:339:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4014:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:3940:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1451:20)
    at Object.bootstrap (http://localhost:3000/bower_components/angular/angular.js:1472:12)
http://errors.angularjs.org/1.3.2/$injector/modulerr?p0=mean&p1=Error%3A%20…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1472%3A12)
```

**Comment by VikramTiwari** [comment]
Old issue and unrelated now. If any questions please ask in gitter chatroom (https://gitter.im/linnovate/mean).
