### ISSUE TITLE
Error: dependency 'socket' was not registered

### ISSUE THREAD

**Issue by Tyvain** [linnovate/mean#993]
I havez a problem launching my app since I add 'comments' and 'mean-admin'a pacjage (it was ok before that):

```

C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces>grunt
Running "hook" task
>> Starting hooked tasks.

Running "clean:0" (clean) task
>> 0 paths cleaned.

Running "jshint:all" (jshint) task
>> 47 files lint free.

Running "csslint:src" (csslint) task
>> 5 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Waiting...
Running "nodemon:dev" (nodemon) task
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
Mongoose: packages.findOne({ name: 'config' }) { fields: undefined }
Mean app started on port 3000 (development) cluster.worker.id: 0
Mongoose: users.ensureIndex({ email: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: comments.ensureIndex({ user: 1 }) { safe: undefined, background: true }

C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\meanio\node_modules\q\q.js:128
                    throw e;
                          ^
Error: dependency 'socket' was not registered
    at get (C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\dependable\index.js:115:15)
    at C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\dependable\index.js:124:18
    at Array.map (native)
    at Meanio.get (C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\dependable\index.js:120:39)
    at enableModules (C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\meanio\lib\module.js:94:2
4)
    at findModulesDone (C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\meanio\lib\module.js:19
:5)
    at _fulfilled (C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\meanio\node_modules\q\q.js:7
94:54)
    at self.promiseDispatch.done (C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\meanio\node_m
odules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\meanio\
node_modules\q\q.js:756:13)
    at C:\BitNami\meanstack-2.4.9-0\projects\fast-annonces\node_modules\meanio\node_modules\q\q.js:564:44
[nodemon] app crashed - waiting for file changes before starting...

```

Any idea?

**Comment by dipen** [comment]
You need to install socket package as comments depend on it --  

```
  mean install socket
```

Also checkout -- https://git.mean.io/pratik/comments/tree/master for integration instructions.

**Comment by liorkesos** [comment]
Mean install comments

**Comment by Tyvain** [comment]
mean install socket -> solved it!

Thank you very much

**Comment by dipen** [comment]
@Tyvain great! btw u can also contact us on https://gitter.im/linnovate/mean for instant relief. In fact thats where most of the support queries should be.

**Comment by weera00** [comment]
npm install -g
